import { ContentIdea, ResearchRequest, ContentGap, CompetitorResult, TargetMarket } from '../../src/types/index.js';
import { normalizeTopic, cleanTemplateText } from './topicNormalizer.js';
import { detectTopicDomain, DetectedTopicInfo } from './domainDetector.js';

interface IdeaTemplateSpec {
  title: string;
  angle: string;
  format: string;
  gapExploited: string;
  targetAudiencePainPoint: string;
  viralityPotential: 'Exceptional' | 'Very High' | 'High' | 'Medium';
  competitionLevel: 'Low' | 'Medium' | 'High';
  whyItWins: string;
}

function buildCookingIdeas(subject: string, market: TargetMarket, isShorts: boolean): IdeaTemplateSpec[] {
  if (market === 'pt-PT') {
    return [
      {
        title: `O Maior Erro ao Fazer ${subject} que Deixa a Massa Seca (E Como Acertar)`,
        angle: 'Desmistificação de temperatura do forno e ordem de mistura com demonstração prática.',
        format: isShorts ? 'Shorts 45s com Gancho de Quebra de Padrão' : 'Vídeo Longo 12min Passo a Passo na Bancada',
        gapExploited: 'Vídeos que mostram apenas a montagem bonita sem explicar porque a massa solou ou secou.',
        targetAudiencePainPoint: 'Frustração de gastar ingredientes e o bolo sair pesado, duro ou queimado.',
        viralityPotential: 'Exceptional',
        competitionLevel: 'Low',
        whyItWins: 'Resolve o maior medo de quem cozinha em casa e gera partilha imediata.',
      },
      {
        title: `Como Fazer ${subject} Perfeito do Zero Passo a Passo (Sem Complicações)`,
        angle: 'Receita infalível calibrada para ingredientes comuns de supermercado português.',
        format: isShorts ? 'Reel de 50s em 3 Etapas' : 'Vídeo de 14min Tutorial para Leigos',
        gapExploited: 'Receitas traduzidas com medidas americanas confusas (chávenas e ingredientes raros).',
        targetAudiencePainPoint: 'Insegurança por não ter batedeira profissional ou formas especiais.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Acessível para qualquer pessoa, com medidas exatas em gramas.',
      },
      {
        title: `Ingredientes de Marca vs Marca Branca para ${subject}: O Que Realmente Vale a Pena?`,
        angle: 'Teste cego sem patrocínios comparando farinha e chocolate caros vs básicos de supermercado.',
        format: isShorts ? 'TikTok 40s com Prova Cega' : 'Vídeo 15min Comparativo Completo',
        gapExploited: 'Mito de que para fazer uma boa sobremesa é obrigatório gastar uma fortuna.',
        targetAudiencePainPoint: 'Dúvida se vale a pena pagar o dobro por marcas premium.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Apelo de poupança no supermercado com autoridade visual inquestionável.',
      },
      {
        title: `Porque é que 90% das Pessoas Erram o Ponto de ${subject} (E o Segredo dos Pasteleiros)`,
        angle: 'Explicação visual da ciência simples do fermento e temperatura dos ovos.',
        format: isShorts ? 'Shorts 45s de Choque de Realidade' : 'Vídeo 11min Segredo de Pastelaria',
        gapExploited: 'Falta de conteúdo explicativo sobre o comportamento térmico dos ingredientes.',
        targetAudiencePainPoint: 'Bolo que abate no centro ou fica com crosta dura.',
        viralityPotential: 'High',
        competitionLevel: 'Medium',
        whyItWins: 'Ativa a curiosidade e entrega um truque prático imediato.',
      },
      {
        title: `A Minha Receita de 15 Minutos de Preparação para ${subject} Sem Sujar a Cozinha Toda`,
        angle: 'Método de uma só tigela (one-bowl) para dias de semana.',
        format: isShorts ? 'POV Timelapse 35s' : 'Vídeo 10min Receita Express',
        gapExploited: 'Receitas demoradas que deixam uma pilha gigante de loiça para lavar.',
        targetAudiencePainPoint: 'Falta de tempo para receitas complicadas e cansativas.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Baixo atrito de execução converte visualizações em salvamentos nos favoritos.',
      },
      {
        title: `A Regra Não Escrita do Forno em Portugal para ${subject}`,
        angle: 'Calibração de fornos domésticos ventilados vs estáticos a 160°C - 180°C.',
        format: isShorts ? 'Shorts 40s Dica Rápida' : 'Vídeo 12min Masterclass de Forno',
        gapExploited: 'Ignorar as variações térmicas comuns nos fornos das casas portuguesas.',
        targetAudiencePainPoint: 'Receita que queimou por fora mas ficou crua no meio.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Especificidade técnica explicada de forma simples e acolhedora.',
      },
      {
        title: `3 Erros ao Fazer ${subject} que Parecem Inofensivos Mas Arruínam o Resultado`,
        angle: 'Contrarian: bater a massa em excesso, abrir o forno cedo e ingredientes frios.',
        format: isShorts ? 'Reel de 40s com 3 Cortes Rápidos' : 'Vídeo 12min Erros Críticos',
        gapExploited: 'Maus hábitos perpetuados por vídeos rápidos sem fundamentação.',
        targetAudiencePainPoint: 'Repetir sempre os mesmos erros sem perceber onde está a falha.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Gera debate fervoroso nos comentários ("eu fazia sempre isso!").',
      },
      {
        title: `Como Fazer ${subject} Macio e Húmido Sem Batedeira nem Máquinas Caras`,
        angle: 'Técnica manual simples usando apenas uma vara de arames ou colher de pau.',
        format: isShorts ? 'Shorts 45s com Checklist' : 'Vídeo 13min Passo a Passo Manual',
        gapExploited: 'Canais que assumem que toda a gente tem batedeiras planetárias caras.',
        targetAudiencePainPoint: 'Achar que culinária de qualidade exige eletrodomésticos caros.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Democratiza a receita para estudantes e lares simples.',
      },
      {
        title: `Testei a Receita Viral de ${subject} do TikTok por 3 Dias (Vale Mesmo a Pena?)`,
        angle: 'Auditoria honesta de "hacks" virais com notas de sabor, custo e textura.',
        format: isShorts ? 'TikTok 55s Formato Review' : 'Vídeo 16min Teste Empírico',
        gapExploited: 'Vídeos que viralizam receitas absurdas que na prática não funcionam.',
        targetAudiencePainPoint: 'Cansaço de cair em receitas da moda que dão errado.',
        viralityPotential: 'Exceptional',
        competitionLevel: 'Low',
        whyItWins: 'Storytelling de teste autêntico gera confiança inabalável.',
      },
      {
        title: `Os 5 Ingredientes de Supermercado que Elevam Qualquer ${subject} ao Nível de Pastelaria`,
        angle: 'Pequenos toques profissionais: flor de sal, cacau de teor correto, aroma natural.',
        format: isShorts ? 'Reel 45s Dicas de Ouro' : 'Vídeo 14min Segredos de Chefe',
        gapExploited: 'Falta de dicas de tempero e intensidade de sabor em doces.',
        targetAudiencePainPoint: 'Receita com sabor monótono ou excessivamente açucarado.',
        viralityPotential: 'Very High',
        competitionLevel: 'Medium',
        whyItWins: 'Promessa de transformação imediata com produtos baratos.',
      },
      {
        title: `O Que Fazer Quando ${subject} Afunda no Centro (Como Salvar sem Deitar Fora)`,
        angle: 'Truques de cobertura e reaproveitamento para nunca desperdiçar ingredientes.',
        format: isShorts ? 'Shorts 40s Solução Rápida' : 'Vídeo 10min Guia de Resgate',
        gapExploited: 'Inexistência de guias de emergência para quando a receita dá para o torto.',
        targetAudiencePainPoint: 'Pânico de estragar a sobremesa no dia em que tem visitas.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Resolve uma emergência real e gera imensos guardados.',
      },
      {
        title: `A Versão Mais Leve e Equilibrada de ${subject} Sem Perder o Sabor`,
        angle: 'Ajuste inteligente de açúcares e gorduras sem recorrer a adoçantes estranhos.',
        format: isShorts ? 'Reel 45s Antes e Depois' : 'Vídeo 13min Receita Equilibrada',
        gapExploited: 'Extremos entre receitas hipercalóricas ou versões fitness sem sabor.',
        targetAudiencePainPoint: 'Desejo de comer um doce delicioso sem peso na consciência.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Conecta com o público que quer equilíbrio e prazer à mesa.',
      },
      {
        title: `Como Conservar ${subject} para Ficar Tão Fresco no 3º Dia Como no Primeiro`,
        angle: 'Dicas de armazenamento, recipientes herméticos e temperatura correta.',
        format: isShorts ? 'Shorts 35s Dica de Conservação' : 'Vídeo 9min Guia de Conservação',
        gapExploited: 'Vídeos que só mostram o bolo quente e esquecem o dia seguinte.',
        targetAudiencePainPoint: 'Bolo que fica ressequido 24 horas após ser fatiado.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Utilidade diária prática com elevado valor para famílias.',
      },
      {
        title: `A Regra 80/20 em ${subject}: Os 2 Passos que Definem 80% do Sucesso da Receita`,
        angle: 'Foco no essencial: emulsão correta dos ovos e descanso da massa.',
        format: isShorts ? 'TikTok 45s Resumo Estratégico' : 'Vídeo 11min Técnica Pura',
        gapExploited: 'Excesso de detalhes inúteis que baralham o cozinheiro principiante.',
        targetAudiencePainPoint: 'Sobrecarga de instruções contraditórias na internet.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Clareza absoluta e simplicidade cativam a audiência.',
      },
      {
        title: `Perguntas e Respostas: As 10 Dúvidas Mais Comuns Sobre ${subject}`,
        angle: 'Esclarecimento cirúrgico de comentários reais de quem tentou fazer a receita.',
        format: isShorts ? 'Reel 50s com Perguntas Rápidas' : 'Vídeo 15min FAQ Completo',
        gapExploited: 'Dúvidas pontuais que nunca são respondidas nos vídeos principais.',
        targetAudiencePainPoint: 'Incerteza sobre substituições de ingredientes.',
        viralityPotential: 'Medium',
        competitionLevel: 'Low',
        whyItWins: 'Humaniza o canal e resolve fricções específicas.',
      },
      {
        title: `A Ficha de Receita Completa de ${subject}: Medidas em Gramas Prontas para Guardar`,
        angle: 'Resumo visual limpo para guardar no telemóvel e usar sempre na cozinha.',
        format: isShorts ? 'Shorts 40s com Cartão de Receita' : 'Vídeo 10min Ficha Técnica',
        gapExploited: 'Dificuldade em pausar vídeos para anotar quantidades.',
        targetAudiencePainPoint: 'Perder a receita e ter de procurar o vídeo novamente.',
        viralityPotential: 'Exceptional',
        competitionLevel: 'Low',
        whyItWins: 'Taxa máxima de favoritos e partilhas diretas no WhatsApp.',
      },
    ];
  }

  // en-GB cooking
  return [
    {
      title: `The #1 Mistake When Making ${subject} in UK Kitchens (And How to Fix It)`,
      angle: 'Troubleshooting oven temperatures and flour texture with live side-by-side bakes.',
      format: isShorts ? 'Shorts 45s Pattern Interrupt' : '12min Kitchen Breakdown',
      gapExploited: 'Viral recipes that omit why bakes sink or dry out in British domestic fan ovens.',
      targetAudiencePainPoint: 'Wasting expensive butter and chocolate on dry, sunken bakes.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'Directly addresses the primary home baker fear with clear visual evidence.',
    },
    {
      title: `How to Make Perfect ${subject} from Scratch (Foolproof UK Step-by-Step)`,
      angle: 'Clear metric recipe (grams and millilitres) using standard UK supermarket staples.',
      format: isShorts ? 'Reel 50s 3-Step Walkthrough' : '14min Complete Beginner Guide',
      gapExploited: 'Cluttered US recipes using imprecise cup measurements and hard-to-find ingredients.',
      targetAudiencePainPoint: 'Confusion when converting cups to grams and Fahrenheit to Celsius.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Tailored specifically for British supermarket staples (plain flour, caster sugar).',
    },
    {
      title: `Supermarket Basics vs Top-Tier Brands for ${subject}: Can You Taste the Difference?`,
      angle: 'Unsponsored blind taste test comparing Aldi/Tesco basics against premium baking brands.',
      format: isShorts ? 'Shorts 40s Blind Taste Test' : '15min Honest Ingredient Comparison',
      gapExploited: 'The elitist belief that delicious bakes require luxury specialist chocolate.',
      targetAudiencePainPoint: 'Tight household food budgets during the cost-of-living squeeze.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Empowers viewers to save genuine cash without sacrificing dessert quality.',
    },
    {
      title: `Why 90% of Bakes of ${subject} Go Wrong (And the Professional Baker's Secret)`,
      angle: 'Simple food chemistry: room temperature eggs, leavening agents, and folding technique.',
      format: isShorts ? 'TikTok 45s Reality Check' : '11min Baker\'s Masterclass',
      gapExploited: 'Superficial videos showing glamorous finished dishes without baking fundamentals.',
      targetAudiencePainPoint: 'Dense, rubbery texture caused by overworking gluten.',
      viralityPotential: 'High',
      competitionLevel: 'Medium',
      whyItWins: 'Delivers an "aha moment" that transforms the viewer\'s kitchen skills.',
    },
    {
      title: `The 15-Minute Prep One-Bowl ${subject} with Minimal Washing Up`,
      angle: 'Streamlined method using a single mixing bowl and a whisk.',
      format: isShorts ? 'POV Timelapse 35s' : '10min One-Bowl Demonstration',
      gapExploited: 'Recipes that demand four separate bowls and a mountain of washing up.',
      targetAudiencePainPoint: 'Dreading the kitchen clean-up after baking.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Low friction prep guarantees peak bookmark rates.',
    },
    {
      title: `The Unwritten Fan Oven Rule for ${subject} in British Kitchens`,
      angle: 'Calibrating standard UK fan-assisted ovens at 160°C to avoid scorched edges.',
      format: isShorts ? 'Shorts 40s Quick Tip' : '12min Oven Science',
      gapExploited: 'Recipes stating generic temperatures without distinguishing fan vs conventional.',
      targetAudiencePainPoint: 'Edges burning before the centre is fully baked.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Highly specific technical clarity that saves real bakes.',
    },
    {
      title: `3 Popular Baking Hacks for ${subject} That Are an Absolute Waste of Time`,
      angle: 'Debunking pointless viral social media trends with side-by-side comparisons.',
      format: isShorts ? 'Reel 40s 3 Fast Cuts' : '12min Myth-Busting Audit',
      gapExploited: 'Gimmicky TikTok cooking hacks that actually ruin the final bake.',
      targetAudiencePainPoint: 'Wasting time on complicated tricks that do not improve flavour.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Contrarian truth-telling always triggers passionate engagement.',
    },
    {
      title: `How to Make ${subject} Soft and Fudgy Without an Electric Stand Mixer`,
      angle: 'Proven manual technique using a wooden spoon or handheld whisk.',
      format: isShorts ? 'Shorts 45s Hand Technique' : '13min Equipment-Free Guide',
      gapExploited: 'Assuming every viewer owns an expensive KitchenAid stand mixer.',
      targetAudiencePainPoint: 'Feeling excluded from baking due to lack of expensive gadgets.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Accessible and reassuring for students and budget-conscious cooks.',
    },
    {
      title: `I Tested the 3 Most Famous Online Recipes for ${subject} (Unfiltered Results)`,
      angle: 'Rigorous bake-off evaluating BBC Good Food, Mary Berry, and viral social recipes.',
      format: isShorts ? 'TikTok 55s Bake-Off Review' : '16min Honest Review Experiment',
      gapExploited: 'Lack of neutral comparisons between the UK\'s most famous recipes.',
      targetAudiencePainPoint: 'Not knowing which famous online recipe actually delivers the best bake.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'Authentic empirical testing creates undisputed creator credibility.',
    },
    {
      title: `5 Secret Supermarket Ingredients That Elevate ${subject} to Bakery Standard`,
      angle: 'Simple additions: a pinch of espresso powder, Maldon sea salt flakes, and dark cocoa.',
      format: isShorts ? 'Reel 45s Secret Ingredients' : '14min Flavour Elevation Guide',
      gapExploited: 'Recipes that produce bland, overly sweet bakes lacking depth.',
      targetAudiencePainPoint: 'Disappointment when home bakes taste one-dimensional compared to artisan bakeries.',
      viralityPotential: 'Very High',
      competitionLevel: 'Medium',
      whyItWins: 'Affordable luxury tweaks that create an immediate flavour upgrade.',
    },
    {
      title: `What to Do When ${subject} Sinks in the Middle (The Emergency Kitchen Rescue)`,
      angle: 'Clever presentation fixes and delicious fillings to salvage the bake gracefully.',
      format: isShorts ? 'Shorts 40s Emergency Fix' : '10min Rescue Masterclass',
      gapExploited: 'Zero guidance for home bakers when things go slightly wrong on the day of an event.',
      targetAudiencePainPoint: 'Panic when preparing food for guests and having an imperfect bake.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Provides urgent practical utility when viewers need it most.',
    },
    {
      title: `The Perfectly Balanced, Not-Too-Sweet ${subject} Recipe`,
      angle: 'Balancing cocoa acidity and sugar levels for deep flavour without cloying sweetness.',
      format: isShorts ? 'Reel 45s Flavour Balance' : '13min Recipe Breakdown',
      gapExploited: 'Extreme oversaturation of sickly sweet icing and tooth-rotting sugar bombs.',
      targetAudiencePainPoint: 'Adult viewers wanting refined, chocolatey flavour without a sugar headache.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Resonates strongly with mature, health-conscious home cooks.',
    },
    {
      title: `How to Store ${subject} So It Stays as Moist on Day 3 as Day 1`,
      angle: 'Correct airtight containers, ambient storage tips, and freezing slices.',
      format: isShorts ? 'Shorts 35s Storage Tip' : '9min Freshness Masterclass',
      gapExploited: 'Recipes that only discuss serving immediately warm out of the oven.',
      targetAudiencePainPoint: 'Bakes drying out into hard crumbs after 24 hours on the counter.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Practical household usefulness that viewers bookmark for future reference.',
    },
    {
      title: `The 80/20 Rule for ${subject}: The 2 Factors That Determine 80% of the Bake`,
      angle: 'Focusing strictly on accurate weighing and avoiding over-baking by 3 minutes.',
      format: isShorts ? 'TikTok 45s Essential Rules' : '11min Principle Walkthrough',
      gapExploited: 'Overwhelming beginners with 20 fussy steps instead of the 2 critical ones.',
      targetAudiencePainPoint: 'Information overload and culinary anxiety.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Gives beginners calm confidence by simplifying the process.',
    },
    {
      title: `UK Baking Q&A: The Top 10 Questions About ${subject} Answered`,
      angle: 'Addressing real community dilemmas regarding flour substitutes, tin liners, and timings.',
      format: isShorts ? 'Reel 50s Rapid Fire Answers' : '15min Comprehensive FAQ',
      gapExploited: 'Specific edge-case queries that standard video descriptions ignore.',
      targetAudiencePainPoint: 'Hesitation due to lacking one specific ingredient at home.',
      viralityPotential: 'Medium',
      competitionLevel: 'Low',
      whyItWins: 'Fosters an engaged, loyal community around practical advice.',
    },
    {
      title: `The Printable One-Page Recipe Card for ${subject}: Exact Weights & Celsius Temperatures`,
      angle: 'Clean visual summary card designed for saving directly to phone camera rolls.',
      format: isShorts ? 'Shorts 40s Save-to-Phone Card' : '10min Printable Walkthrough',
      gapExploited: 'Having to scrub back and forth through a 15-minute video while hands are covered in flour.',
      targetAudiencePainPoint: 'Friction of pausing video tutorials mid-bake.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'Peak bookmark and share rates across social media algorithms.',
    },
  ];
}

function buildGardeningIdeas(subject: string, market: TargetMarket, isShorts: boolean): IdeaTemplateSpec[] {
  const isUK = market === 'en-GB';
  return [
    {
      title: isUK ? `The Fatal Mistake with ${subject} in UK Gardens (And How to Fix It)` : `O Maior Erro com ${subject} que Queima as Raízes (E Como Evitar)`,
      angle: 'Troubleshooting soil drainage, seasonal planting, and watering.',
      format: isShorts ? 'Shorts 45s Warning' : '12min Practical Guide',
      gapExploited: 'Generic advice that ignores local rainfall, frost dates, or summer heat.',
      targetAudiencePainPoint: 'Seedlings wilting or rotting before flowering.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'Saves real plants and prevents frustration for beginner gardeners.',
    },
    {
      title: isUK ? `How to Grow ${subject} from Scratch on a Budget` : `Como Cultivar ${subject} do Zero com Orçamento Reduzido`,
      angle: 'Beginner container and patio setup using repurposed pots and affordable compost.',
      format: isShorts ? 'Reel 50s 3-Step Setup' : '14min Beginner Blueprint',
      gapExploited: 'Guides that assume viewers have huge plots of land and expensive gardening tools.',
      targetAudiencePainPoint: 'Thinking gardening is too expensive or impossible in small urban spaces.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Democratises gardening for urban dwellers and beginners.',
    },
    {
      title: isUK ? `Bargain Compost vs Specialist Soil for ${subject}: The Honest Test` : `Substrato Barato vs Terra Especial para ${subject}: Vale a Pena?`,
      angle: 'Unsponsored growth test comparing budget supermarket bags with premium garden centre mixes.',
      format: isShorts ? 'TikTok 40s Growth Test' : '15min Comparison Audit',
      gapExploited: 'Expensive soil marketing that confuses newcomers.',
      targetAudiencePainPoint: 'Wondering if expensive compost makes any real difference to plant vigour.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'High-value consumer advice with visible green results.',
    },
    {
      title: isUK ? `Why 90% of Seedlings of ${subject} Fail (And the Secret of the 10%)` : `Porque é que 90% das Mudas de ${subject} Morrem (E o Segredo para Salvar)`,
      angle: 'Addressing over-watering, damping off, and insufficient natural light.',
      format: isShorts ? 'Shorts 45s Reality Check' : '11min Troubleshooting Walkthrough',
      gapExploited: 'Failing to explain the critical first 3 weeks of seedling care.',
      targetAudiencePainPoint: 'Watching seedlings sprout and then collapse within days.',
      viralityPotential: 'High',
      competitionLevel: 'Medium',
      whyItWins: 'Eliminates the #1 reason beginners give up on gardening.',
    },
    {
      title: isUK ? `The 10-Minute Weekly Maintenance Routine for ${subject}` : `A Rotina Semanal de 10 Minutos para Manter ${subject} Saudável`,
      angle: 'Minimalist checklist: targeted watering, checking leaf undersides, and deadheading.',
      format: isShorts ? 'POV 35s Routine' : '10min Routine Walkthrough',
      gapExploited: 'Gardening videos that make plant care sound like a full-time job.',
      targetAudiencePainPoint: 'Busy work schedules with little time for daily gardening.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Low friction and daily feasibility.',
    },
    {
      title: isUK ? `The Unwritten UK Frost & Pruning Rule for ${subject}` : `A Regra Não Escrita de Rega e Poda para ${subject}`,
      angle: 'Local seasonal nuances that prevent cold snaps or scorched roots from killing plants.',
      format: isShorts ? 'Shorts 40s Quick Tip' : '12min Seasonal Masterclass',
      gapExploited: 'Imported guides with the wrong calendar dates.',
      targetAudiencePainPoint: 'Pruning too early or planting before the final frost.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Essential local seasonal knowledge.',
    },
    {
      title: isUK ? `3 Common Plant Care Trends That Actually Harm ${subject}` : `3 Erros Comuns no Cuidado de ${subject} que Deves Parar Hoje`,
      angle: 'Debunking excessive chemical sprays, incorrect fertilising, and tight repotting.',
      format: isShorts ? 'Reel 40s 3 Fast Cuts' : '12min Myth-Buster',
      gapExploited: 'Gimmicky internet gardening hacks that do more harm than good.',
      targetAudiencePainPoint: 'Conflicting advice on online forums.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Builds trust through sober, grounded botanical sense.',
    },
    {
      title: isUK ? `How to Grow ${subject} in Pots and Small Balconies` : `Como Ter ${subject} em Vasos e Varandas Pequenas`,
      angle: 'Container sizing, drainage holes, and balcony wind protection.',
      format: isShorts ? 'Shorts 45s Balcony Guide' : '13min Urban Gardening Blueprint',
      gapExploited: 'Lack of container-specific tutorials for renters and flat dwellers.',
      targetAudiencePainPoint: 'Living in an apartment without an outdoor lawn or garden bed.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Expands the addressable audience to urban renters.',
    },
    {
      title: isUK ? `I Tested 3 Ways to Propagate ${subject} (30-Day Growth Results)` : `Testei 3 Formas de Propagar ${subject} (Resultados Reais ao Fim de 30 Dias)`,
      angle: 'Direct test of cuttings in water, soil, and direct rooting hormones.',
      format: isShorts ? 'TikTok 55s Time-Lapse' : '16min 30-Day Experiment',
      gapExploited: 'Videos showing cuttings being made but never showing root development weeks later.',
      targetAudiencePainPoint: 'Cuttings rotting instead of striking healthy roots.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'Compelling visual proof and satisfying progression.',
    },
    {
      title: isUK ? `5 Natural Household Ingredients That Help ${subject} Thrive Without Chemicals` : `5 Ingredientes Caseiros que Adubam ${subject} Sem Químicos Caros`,
      angle: 'Eggshell calcium, coffee ground acidity balance, and natural weed suppression.',
      format: isShorts ? 'Reel 45s Organic Secrets' : '14min Natural Feed Guide',
      gapExploited: 'Over-reliance on synthetic fertilisers that harm soil microbiology.',
      targetAudiencePainPoint: 'Wanting organic, pet-safe plant care without spending a fortune.',
      viralityPotential: 'Very High',
      competitionLevel: 'Medium',
      whyItWins: 'Free, eco-friendly kitchen hacks for the garden.',
    },
    {
      title: isUK ? `How to Protect ${subject} from Slugs, Aphids & Common Pests Organically` : `Como Proteger ${subject} de Pragas sem Venenos Perigosos`,
      angle: 'Physical barriers, companion planting, and natural soap sprays.',
      format: isShorts ? 'Shorts 40s Pest Hack' : '10min Organic Pest Blueprint',
      gapExploited: 'Videos recommending harsh poisons harmful to pets and pollinators.',
      targetAudiencePainPoint: 'Waking up to find tender new shoots devoured by slugs overnight.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'High-urgency problem solving that saves viewers\' hard work.',
    },
    {
      title: isUK ? `How to Water ${subject} Properly: Why Morning vs Evening Matters` : `A Forma Correta de Regar ${subject}: Porque a Hora do Dia Faz Toda a Diferença`,
      angle: 'Evaporation rates, fungal leaf prevention, and deep soaking vs shallow sprinkles.',
      format: isShorts ? 'Reel 45s Watering Technique' : '11min Hydration Guide',
      gapExploited: 'Assuming watering is just wetting the surface soil.',
      targetAudiencePainPoint: 'Mildew on leaves and shallow root systems.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Simple tweak with massive visual impact on plant health.',
    },
    {
      title: isUK ? `The Signs Your ${subject} Needs Repotting (And How to Do It Without Shock)` : `Como Saber Quando Mudar ${subject} de Vaso Sem Matar a Planta`,
      angle: 'Root-bound diagnosis and gentle root loosening technique.',
      format: isShorts ? 'Shorts 35s Repotting Checklist' : '12min Repotting Walkthrough',
      gapExploited: 'Transplant shock killing mature plants during pot upgrades.',
      targetAudiencePainPoint: 'Fear of disturbing healthy roots.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Practical confidence builder for indoor and outdoor plant lovers.',
    },
    {
      title: isUK ? `The 80/20 Rule in Plant Care: The 2 Things That Guarantee Success with ${subject}` : `A Regra 80/20 na Jardinagem: Os 2 Hábitos Essenciais para ${subject}`,
      angle: 'Focus on correct lighting location and proper drainage holes.',
      format: isShorts ? 'TikTok 45s Essential Rules' : '10min Principle Guide',
      gapExploited: 'Complicated botanical instructions that paralyse the gardener.',
      targetAudiencePainPoint: 'Over-thinking plant care routines.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Cuts through fluff with serene clarity.',
    },
    {
      title: isUK ? `Gardening Q&A: Answering the 10 Most Common Questions on ${subject}` : `Perguntas e Respostas: As 10 Dúvidas Mais Comuns Sobre ${subject}`,
      angle: 'Resolving real community problems regarding yellow leaves, flowering, and winter care.',
      format: isShorts ? 'Reel 50s Rapid Fire' : '15min Q&A Guide',
      gapExploited: 'Specific grower dilemmas that general guides gloss over.',
      targetAudiencePainPoint: 'Not knowing why a specific plant has stopped growing.',
      viralityPotential: 'Medium',
      competitionLevel: 'Low',
      whyItWins: 'Builds dedicated niche community followers.',
    },
    {
      title: isUK ? `The Complete Seasonal Calendar for ${subject}: What to Do Month-by-Month` : `O Calendário Completo de Cuidados para ${subject}: O Que Fazer Mês a Mês`,
      angle: 'Concise visual guide detailing planting, feeding, pruning, and dormant seasons.',
      format: isShorts ? 'Shorts 40s Saveable Calendar' : '13min Year-Round Guide',
      gapExploited: 'Gardening guides that cover one day rather than year-round plant lifecycle.',
      targetAudiencePainPoint: 'Forgetting when to feed or prepare plants for winter.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'Peak bookmark and share rates for year-round reference.',
    },
  ];
}

function buildHealthIdeas(subject: string, market: TargetMarket, isShorts: boolean): IdeaTemplateSpec[] {
  const isUK = market === 'en-GB';
  return [
    {
      title: isUK ? `The #1 Unsustainable Mistake with ${subject} (And How to Fix It)` : `O Maior Erro em ${subject} que Faz 90% das Pessoas Desistirem`,
      angle: 'Replacing extreme restrictive fads with realistic, nutrient-dense habits.',
      format: isShorts ? 'Shorts 45s Pattern Interrupt' : '12min Wellness Blueprint',
      gapExploited: 'Influencer diets that demand 2 hours in the gym and eating boiled chicken daily.',
      targetAudiencePainPoint: 'Exhaustion, low energy, and quitting after two weeks.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'Relieves guilt and provides an achievable, grounded health path.',
    },
    {
      title: isUK ? `Quick High-Protein Meals for ${subject} Ready in Under 15 Minutes` : `Refeições Rápidas de Alta Proteína para ${subject} Prontas em 15 Minutos`,
      angle: 'Fast, hearty whole-food meals using standard supermarket staples.',
      format: isShorts ? 'Reel 50s 3-Recipe Reel' : '14min Meal Prep Walkthrough',
      gapExploited: '90-minute complicated Sunday meal prep routines that no busy person can maintain.',
      targetAudiencePainPoint: 'Coming home exhausted from work and ordering unhealthy takeaway.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Solves the acute evening dilemma with delicious, fast nourishment.',
    },
    {
      title: isUK ? `Whole Supermarket Foods vs Expensive Powders for ${subject}` : `Comida de Supermercado vs Suplementos Caros para ${subject}: A Verdade`,
      angle: 'Unsponsored nutritional audit comparing eggs, Greek yoghurt, and tinned fish against expensive powders.',
      format: isShorts ? 'TikTok 40s Comparison' : '15min Honest Nutrition Audit',
      gapExploited: 'Aggressive sponsored supplement peddling on fitness social media.',
      targetAudiencePainPoint: 'Spending £80+ a month on tubs of powders with zero visible change.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Saves household money while improving real nutritional vitality.',
    },
    {
      title: isUK ? `Why 90% Fail to Maintain Progress in ${subject} (And the Consistency Secret)` : `Porque é que 90% Falham em ${subject} (E o Segredo da Consistência)`,
      angle: 'Habit stacking, friction reduction, and keeping energy stable throughout the workday.',
      format: isShorts ? 'Shorts 45s Reality Check' : '11min Behavioural Masterclass',
      gapExploited: 'Glorifying extreme willpower over intelligent environmental design.',
      targetAudiencePainPoint: 'The rollercoaster cycle of motivation followed by crash burnout.',
      viralityPotential: 'High',
      competitionLevel: 'Medium',
      whyItWins: 'Actionable psychology that viewers can implement immediately.',
    },
    {
      title: isUK ? `The 15-Minute Daily Routine for Energy, Mobility & Strength with ${subject}` : `A Rotina Diária de 15 Minutos para Vitalidade e Mobilidade em ${subject}`,
      angle: 'Joint-friendly functional movements and breakfast habits for busy adults.',
      format: isShorts ? 'POV 35s Routine' : '12min Follow-Along Routine',
      gapExploited: 'Extreme workout videos that cause joint pain for mature or working adults.',
      targetAudiencePainPoint: 'Stiff joints, morning sluggishness, and lack of exercise time.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Doable at home in ordinary clothes without gym subscriptions.',
    },
    {
      title: isUK ? `The Unwritten Sleep & Hydration Rule Behind ${subject}` : `A Regra Essencial de Sono e Hidratação para Potenciar ${subject}`,
      angle: 'How sleep architecture and morning hydration drive 70% of vitality and appetite control.',
      format: isShorts ? 'Shorts 40s Science Tip' : '11min Recovery Masterclass',
      gapExploited: 'Obsessing over workouts while ignoring chronic sleep deprivation.',
      targetAudiencePainPoint: 'Brain fog and mid-afternoon energy crashes.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Focuses on the foundation of wellness without selling products.',
    },
    {
      title: isUK ? `3 Health 'Hacks' for ${subject} That Are Completely Useless` : `3 Modismos da Internet sobre ${subject} que Só Fazem Perder Tempo`,
      angle: 'Exposing useless fat-burning teas, extreme cold plunge hype, and overpriced detoxes.',
      format: isShorts ? 'Reel 40s 3 Fast Cuts' : '12min Scam Buster',
      gapExploited: 'Predatory marketing targeting people desperate for fast health transformations.',
      targetAudiencePainPoint: 'Wasting money on fads without experiencing real health benefits.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Sharp, refreshing honesty cut through wellness noise.',
    },
    {
      title: isUK ? `How to Tailor ${subject} for Adults Over 40: Joint Health & Longevity` : `Como Adaptar ${subject} Depois dos 40 Anos: Articulações e Longevidade`,
      angle: 'Slower tempo, higher protein distribution, and joint preservation over ego lifting.',
      format: isShorts ? 'Shorts 45s Longevity Tip' : '14min Over-40 Masterclass',
      gapExploited: 'Fitness channels predominantly catered to 20-year-olds with indestructible joints.',
      targetAudiencePainPoint: 'Knee and shoulder aches when trying standard exercise regimes.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'Massive underserved audience of mature adults with purchasing power.',
    },
    {
      title: isUK ? `I Tracked My Health Markers on ${subject} for 30 Days (Blood & Energy Results)` : `Testei Esta Mudança em ${subject} Durante 30 Dias (Resultados Reais de Energia)`,
      angle: 'Empirical biomarker review showing real improvements in resting heart rate and focus.',
      format: isShorts ? 'TikTok 55s Data Review' : '16min 30-Day Experiment',
      gapExploited: 'Anecdotal claims without auditable before-and-after data.',
      targetAudiencePainPoint: 'Scepticism about whether modest routine changes make a tangible difference.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Transparent personal data generates deep audience trust.',
    },
    {
      title: isUK ? `5 Supermarket Essentials That Keep You Full for Hours with ${subject}` : `5 Alimentos Simples de Supermercado que Saciam por Horas em ${subject}`,
      angle: 'Fibre density, lean proteins, and complex carbohydrates that stop snacking urges.',
      format: isShorts ? 'Reel 45s Satiety Staples' : '13min Shopping Walkthrough',
      gapExploited: 'Diets that leave people hungry, cranky, and obsessing over snacks.',
      targetAudiencePainPoint: 'Constant cravings and willpower fatigue by 3pm.',
      viralityPotential: 'Very High',
      competitionLevel: 'Medium',
      whyItWins: 'Solves hunger at the root using cheap everyday foods.',
    },
    {
      title: isUK ? `How to Stay on Track with ${subject} When Dining Out or Travelling` : `Como Manter os Resultados em ${subject} Mesmo ao Comer Fora ou Viajar`,
      angle: 'Sensible menu selection strategies that let you enjoy social occasions without guilt.',
      format: isShorts ? 'Shorts 40s Restaurant Hack' : '10min Social Life Guide',
      gapExploited: 'Unrealistic advice telling people to bring cold Tupperware to restaurants.',
      targetAudiencePainPoint: 'Fear of ruining progress during social gatherings or weekend trips.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Empowers viewers to live a normal, enjoyable social life.',
    },
    {
      title: isUK ? `The Stress & Cortisol Trap in ${subject}: Why You're Not Seeing Results` : `O Efeito do Stress e Cortisol em ${subject}: Porque Não Vês Resultados`,
      angle: 'Explaining how chronic workplace anxiety inhibits recovery and drives abdominal fat storage.',
      format: isShorts ? 'Reel 45s Stress Connection' : '12min Hormonal Balance Guide',
      gapExploited: 'Treating health purely as a calories-in-calories-out equation.',
      targetAudiencePainPoint: 'Doing everything right with food but still feeling exhausted and bloated.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Validates the viewer\'s lived experience of demanding work pressure.',
    },
    {
      title: isUK ? `The Minimalist Grocery Shopping List for ${subject} Under £30` : `A Lista de Compras Essencial para ${subject} com Menos de 30€`,
      angle: 'Clean trolley audit with exact items and prices for a week of nutritious eating.',
      format: isShorts ? 'Shorts 35s Trolley Tour' : '11min Budget Grocery Walkthrough',
      gapExploited: 'Health advice that assumes an unlimited budget at organic farmers markets.',
      targetAudiencePainPoint: 'Believing that healthy eating is only for the affluent.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Tangible, cost-effective grocery lists get saved and shared endlessly.',
    },
    {
      title: isUK ? `The 80/20 Rule for ${subject}: The 2 Habits That Provide 80% of the Results` : `A Regra 80/20 em ${subject}: Os 2 Hábitos que Geram 80% dos Resultados`,
      angle: 'Prioritising adequate daily protein and 7,500 daily steps over complex training splits.',
      format: isShorts ? 'TikTok 45s Essential Habits' : '10min Principle Guide',
      gapExploited: 'Confusing beginners with 15 minor details that only matter for elite athletes.',
      targetAudiencePainPoint: 'Overwhelmed by contradictory wellness information.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Provides immense psychological relief and clarity.',
    },
    {
      title: isUK ? `Health & Nutrition Q&A: Addressing the 10 Most Common Dilemmas on ${subject}` : `Perguntas e Respostas: As 10 Maiores Dúvidas sobre ${subject}`,
      angle: 'Direct answers on meal timing, coffee intake, carb consumption, and fatigue.',
      format: isShorts ? 'Reel 50s Rapid Fire Answers' : '15min Comprehensive FAQ',
      gapExploited: 'Nuanced questions that standard fitness videos dismiss.',
      targetAudiencePainPoint: 'Confusion over conflicting advice seen on TikTok and podcasts.',
      viralityPotential: 'Medium',
      competitionLevel: 'Low',
      whyItWins: 'Builds warm trust and authoritative connection.',
    },
    {
      title: isUK ? `The Printable Weekly Habit & Meal Tracker for ${subject}` : `O Guia em Cartão de Hábitos e Refeições Práticas para ${subject}`,
      angle: 'Clean visual summary card designed for saving to phone camera rolls or fridge doors.',
      format: isShorts ? 'Shorts 40s Save-to-Phone Checklist' : '10min Printable Guide',
      gapExploited: 'Lack of practical daily accountability frameworks.',
      targetAudiencePainPoint: 'Starting strong on Monday and drifting off by Thursday.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'Peak bookmark rates across platforms.',
    },
  ];
}

function buildConsumerBudgetingIdeas(subject: string, market: TargetMarket, isShorts: boolean): IdeaTemplateSpec[] {
  const isUK = market === 'en-GB';
  return [
    {
      title: isUK ? `The Sneaky Trolley Trap Costing UK Shoppers on ${subject}` : `A Armadilha Oculta no Supermercado ao Fazer Compras de ${subject}`,
      angle: 'Exposing how shrinkflation and fake promotional tags mislead shoppers on unit pricing (£/kg vs €/kg).',
      format: isShorts ? 'Shorts 45s Trolley Trap' : '13min Supermarket Audit',
      gapExploited: 'Recycled advice saying "make a list" without showing how supermarkets manipulate prices.',
      targetAudiencePainPoint: 'Watching grocery receipts soar despite buying the same items.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'Saves immediate cash at checkout and triggers passionate sharing.',
    },
    {
      title: isUK ? `Real Supermarket Price Audit for ${subject}: Aldi & Lidl vs Tesco & Sainsbury\'s` : `Comparativo Real de Faturas: Onde Fica Mais Barato Comprar ${subject}?`,
      angle: 'Basket-by-basket receipt audit comparing exact staple items across major chains.',
      format: isShorts ? 'Reel 50s Basket Comparison' : '15min Full Receipt Breakdown',
      gapExploited: 'Vague claims about discounters without displaying actual receipts and unit prices.',
      targetAudiencePainPoint: 'Uncertainty about which supermarket genuinely offers the best value.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Field research with transparent proof is irresistible to household budget managers.',
    },
    {
      title: isUK ? `How to Cut Your ${subject} Grocery Bill by 30% Without Eating Bland Food` : `Como Cortar 30% nas Compras de ${subject} Sem Comer Pior`,
      angle: 'Strategic batch cooking, freezer optimisation, and intelligent store cupboard staples.',
      format: isShorts ? 'TikTok 40s Money Saving Hack' : '14min Complete Grocery Strategy',
      gapExploited: 'Extreme couponing that produces unappetising meals nobody wants to eat.',
      targetAudiencePainPoint: 'Feeling deprived when trying to save money on food.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Delivers dignified, flavourful savings.',
    },
    {
      title: isUK ? `Why 90% Overpay on ${subject} at the Checkout (And the Unit Price Fix)` : `Porque é que 90% das Famílias Pagam a Mais em ${subject} Sem Perceber`,
      angle: 'Reading the small print on shelf edges to identify true cost per kilogram or litre.',
      format: isShorts ? 'Shorts 45s Shelf Edge Hack' : '11min Pricing Masterclass',
      gapExploited: 'Lack of shelf-edge unit pricing literacy.',
      targetAudiencePainPoint: 'Falling for "Buy 2 for £3" deals that actually cost more per unit.',
      viralityPotential: 'High',
      competitionLevel: 'Medium',
      whyItWins: 'Simple practical habit that pays off every single week.',
    },
    {
      title: isUK ? `The 15-Minute Weekly Meal Plan for ${subject} That Eliminates Food Waste` : `O Plano de Refeições de 15 Minutos para ${subject} que Reduz o Desperdício a Zero`,
      angle: 'A structured 5-dinner framework that uses overlapping fresh ingredients before they spoil.',
      format: isShorts ? 'POV 35s Meal Plan Tour' : '12min Weekly Planning Blueprint',
      gapExploited: 'Throwing away spoiled salad, herbs, and dairy at the end of every week.',
      targetAudiencePainPoint: 'Throwing real money into the kitchen bin each Sunday.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Stops food waste and saves £40+ a month effortlessly.',
    },
    {
      title: isUK ? `The Yellow-Sticker & Reduced Aisle Strategy for ${subject}` : `O Guia de Descontos de Fim de Dia no Supermercado para ${subject}`,
      angle: 'Timing, freezer safety, and meal repurposing for discounted supermarket produce.',
      format: isShorts ? 'Shorts 40s Yellow Sticker Hack' : '12min Markdown Guide',
      gapExploited: 'Stigma or lack of practical strategy around reduced-to-clear sections.',
      targetAudiencePainPoint: 'Missing out on high-quality proteins and produce at 70% off.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Popular shopping subculture with massive view engagement.',
    },
    {
      title: isUK ? `3 Things You Should Never Buy Pre-Packaged for ${subject}` : `3 Coisas em ${subject} que Nunca Deves Comprar Já Embaladas`,
      angle: 'Pre-grated cheese, bagged chopped veg, and pre-marinated meats that carry a 200% premium.',
      format: isShorts ? 'Reel 40s 3 Fast Comparisons' : '11min Convenience Premium Audit',
      gapExploited: 'Paying exorbitant convenience fees for 30 seconds of prep work.',
      targetAudiencePainPoint: 'Budget bleeding quietly on convenience markup.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Eye-opening visual price differences that shock viewers.',
    },
    {
      title: isUK ? `How to Feed a Family on ${subject} for Under £35 a Week` : `Como Alimentar a Família com ${subject} por Menos de 40€ por Semana`,
      angle: 'Wholesome, filling recipes with lentils, whole chicken breakdown, and seasonal vegetables.',
      format: isShorts ? 'Shorts 45s Family Menu' : '16min Budget Masterclass',
      gapExploited: 'Austerity recipes that taste like cardboard and alienate children.',
      targetAudiencePainPoint: 'Stress of balancing household bills against healthy nutrition.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'Direct, compassionate, high-value public service content.',
    },
    {
      title: isUK ? `I Swapped to Supermarket Own-Brands for ${subject} for 30 Days (Savings & Taste Review)` : `Troquei Todas as Marcas Famosas de ${subject} por Marcas Brancas por 30 Dias`,
      angle: 'Unfiltered audit of quality, taste, and exact bank balance differences after one month.',
      format: isShorts ? 'TikTok 55s Own-Brand Review' : '15min 30-Day Budget Audit',
      gapExploited: 'Unsubstantiated claims about supermarket brand inferiority.',
      targetAudiencePainPoint: 'Fear that own-brand goods taste terrible or compromise health.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Empirical proof that breaks brand snobbery and saves real money.',
    },
    {
      title: isUK ? `5 Supermarket Pantry Staples That Stretch Any ${subject} Meal Further` : `5 Alimentos Baratos de Despensa que Rendem o Dobro em ${subject}`,
      angle: 'Tinned pulses, oats, tinned tomatoes, and versatile spices that bulk up meals nutrition.',
      format: isShorts ? 'Reel 45s Pantry Staples' : '12min Pantry Elevation Guide',
      gapExploited: 'Not knowing how to bulk up dishes healthily on a budget.',
      targetAudiencePainPoint: 'Meals running out quickly and family members staying hungry.',
      viralityPotential: 'Very High',
      competitionLevel: 'Medium',
      whyItWins: 'Practical culinary hacks that stretch household food budgets.',
    },
    {
      title: isUK ? `How to Store Supermarket Fresh Produce for ${subject} to Last 2 Weeks` : `Como Guardar Frutas e Legumes de ${subject} para Durarem 2 Semanas Sem Estragar`,
      angle: 'Water jars, paper towels, and crisper drawer vent adjustments.',
      format: isShorts ? 'Shorts 40s Freshness Hack' : '11min Produce Storage Masterclass',
      gapExploited: 'Buying fresh vegetables that turn to sludge within 4 days.',
      targetAudiencePainPoint: 'Guilt of throwing out rotten produce before it can be cooked.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Direct, tangible visual tips that pay for themselves immediately.',
    },
    {
      title: isUK ? `The Real Truth About Loyalty Cards and 'Clubcard' Prices on ${subject}` : `A Verdade Sobre Cartões de Fidelização e Preços Exclusivos em ${subject}`,
      angle: 'Auditing whether loyalty discounts are genuine bargains or inflated baseline prices.',
      format: isShorts ? 'Reel 45s Loyalty Trap' : '13min Loyalty Card Investigation',
      gapExploited: 'Data harvesting and psychological pricing tactics used by supermarket chains.',
      targetAudiencePainPoint: 'Feeling manipulated by multi-tiered retail pricing schemes.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Investigative consumer edge that builds deep creator authority.',
    },
    {
      title: isUK ? `How to Shop for ${subject} Online vs In-Store: Which Saves More Money?` : `Comprar ${subject} Online vs na Loja Física: Onde se Poupa Mais?`,
      angle: 'Delivery charges vs impulse purchases: an auditable comparison of checkout receipts.',
      format: isShorts ? 'Shorts 35s Online vs In-Store' : '11min Shopping Channel Comparison',
      gapExploited: 'Debating whether delivery pass costs offset supermarket aisle impulse buys.',
      targetAudiencePainPoint: 'Spending £20 extra on unneeded treats every time one walks the aisles.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Pragmatic advice for busy parents and working professionals.',
    },
    {
      title: isUK ? `The 80/20 Rule for Grocery Budgets: The 2 Changes That Cut 80% of Waste in ${subject}` : `A Regra 80/20 no Orçamento de Alimentação: Os 2 Hábitos Essenciais para ${subject}`,
      angle: 'Shop your own freezer and pantry first, and buy meat by unit price (£/kg or €/kg).',
      format: isShorts ? 'TikTok 45s Essential Rules' : '10min Principle Guide',
      gapExploited: 'Obsessing over micro-coupons instead of the primary cost drivers.',
      targetAudiencePainPoint: 'Overcomplicated money-saving spreadsheets that get abandoned.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Simplicity that delivers instant financial peace of mind.',
    },
    {
      title: isUK ? `Budget Supermarket Q&A: Answering Your Top 10 Dilemmas on ${subject}` : `Perguntas e Respostas: As 10 Dúvidas Mais Comuns para Poupar em ${subject}`,
      angle: 'Addressing real community questions on bulk buying, freezer burn, and discount apps.',
      format: isShorts ? 'Reel 50s Rapid Fire Answers' : '14min Comprehensive FAQ',
      gapExploited: 'Niche budgeting dilemmas that traditional media ignores.',
      targetAudiencePainPoint: 'Wondering if buying in bulk is actually cheaper for small households.',
      viralityPotential: 'Medium',
      competitionLevel: 'Low',
      whyItWins: 'Deepens community loyalty and ongoing engagement.',
    },
    {
      title: isUK ? `The Printable Weekly Shopping & Meal Plan Card for ${subject}` : `O Cartão Descarregável de Lista de Compras Inteligente para ${subject}`,
      angle: 'Clean visual summary card designed for saving to phone camera rolls before heading into the store.',
      format: isShorts ? 'Shorts 40s Save-to-Phone Checklist' : '10min Printable Guide',
      gapExploited: 'Walking into supermarkets without a clear, organised visual plan.',
      targetAudiencePainPoint: 'Impulse buying when tired and hungry after work.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'Peak bookmark and share rates across social media algorithms.',
    },
  ];
}

function buildFinanceIdeas(subject: string, market: TargetMarket, isShorts: boolean): IdeaTemplateSpec[] {
  const isUK = market === 'en-GB';
  const isES = market === 'es-ES';
  const isBR = market === 'pt-BR';

  if (isUK) {
    return [
      {
        title: `The Costly HMRC & Fee Blunder with ${subject} in the UK (And How to Fix It)`,
        angle: 'Clear tax year, capital gains, and platform fee breakdown using live dashboards.',
        format: isShorts ? 'Shorts 45s Warning Card' : '14min Complete UK Tax Audit',
        gapExploited: 'Imported US advice that ignores HMRC allowances, ISA limits, and FCA protections.',
        targetAudiencePainPoint: 'Fear of unexpected tax bills or losing returns to high platform fees.',
        viralityPotential: 'Exceptional',
        competitionLevel: 'Low',
        whyItWins: 'Authoritative, UK-grounded guidance that saves viewers genuine thousands.',
      },
      {
        title: `How to Start with ${subject} in the UK with Just £50 to £100 a Month`,
        angle: 'Realistic step-by-step walkthrough tailored for UK median take-home pay.',
        format: isShorts ? 'Reel 50s 3-Step Walkthrough' : '12min Beginner Walkthrough with Real Pounds',
        gapExploited: 'Inflated influencer advice demanding £1,000 monthly contributions.',
        targetAudiencePainPoint: 'Feeling excluded because of modest starting savings.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Connects directly with everyday British workers without condescension.',
      },
      {
        title: `UK High Street Banks vs Modern Platforms for ${subject}: The Real Fees`,
        angle: 'Unvarnished comparison of legacy bank charges vs low-cost UK platforms.',
        format: isShorts ? 'TikTok 40s Fee Table' : '16min Spreadsheet Fee Comparison',
        gapExploited: 'Hidden custody charges and opaque FX markups by traditional providers.',
        targetAudiencePainPoint: 'Overpaying for sluggish legacy banking services.',
        viralityPotential: 'Very High',
        competitionLevel: 'Medium',
        whyItWins: 'Triggers intense discussion and high bookmark rates.',
      },
      {
        title: `Why 90% of UK Beginners Lose Momentum with ${subject} (And the 10% Fix)`,
        angle: 'Debunking short-term trading hype and establishing automated monthly investing.',
        format: isShorts ? 'Shorts 45s Reality Check' : '15min Critical Strategy Analysis',
        gapExploited: 'Tired sensationalist get-rich-quick schemes.',
        targetAudiencePainPoint: 'Frustration from volatile swings and lack of sustainable progress.',
        viralityPotential: 'High',
        competitionLevel: 'Medium',
        whyItWins: 'Appeals to risk-conscious British viewers seeking steady security.',
      },
      {
        title: `My 15-Minute Monthly System for Managing ${subject} in the UK`,
        angle: 'Set-and-forget automation for busy full-time UK professionals.',
        format: isShorts ? 'POV Timelapse 35s' : '10min Routine Walkthrough',
        gapExploited: 'Overcomplicated methods demanding hours of daily chart watching.',
        targetAudiencePainPoint: 'Having zero spare time to research complex finance topics.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Minimal friction and clear automation attract peak engagement.',
      },
      {
        title: `The Unwritten UK HMRC Rules for ${subject} That Change Everything`,
        angle: 'ISA dividend allowances, bed-and-ISA transfers, and CGT exemptions explained simply.',
        format: isShorts ? 'Shorts 45s Tax Nuance' : '13min Case Study',
        gapExploited: 'Vague summaries that fail to explain actionable tax optimisation.',
        targetAudiencePainPoint: 'Confusion around self-assessment and HMRC reporting thresholds.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Delivers undeniable, auditable value for every UK taxpayer.',
      },
      {
        title: `3 Things in ${subject} That Sound Great But Are an Absolute Waste of Money`,
        angle: 'Contrarian teardown of high-fee actively managed funds and predatory courses.',
        format: isShorts ? 'Reel 40s 3 Fast Cuts' : '11min Demystification',
        gapExploited: 'Viewer cynicism towards financial influencers and sponsored products.',
        targetAudiencePainPoint: 'Fear of falling for marketing traps or paying hidden commissions.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Protects viewers\' capital and establishes fierce creator loyalty.',
      },
      {
        title: `How to Build a Long-Term Strategy with ${subject} from Scratch (Zero Jargon)`,
        angle: 'Jargon-free beginner roadmap explaining core mechanics in plain British English.',
        format: isShorts ? 'Shorts 50s Checklist' : '15min Beginner Masterclass',
        gapExploited: 'Intimidating acronyms and financial jargon that alienate novices.',
        targetAudiencePainPoint: 'Feeling embarrassed to ask basic financial questions.',
        viralityPotential: 'High',
        competitionLevel: 'Medium',
        whyItWins: 'Welcomes everyday learners who have been ignored by finance snobs.',
      },
      {
        title: `I Tested the Most Popular UK Strategy for ${subject} for 12 Months (Real Returns)`,
        angle: 'Empirical review featuring open portfolio numbers, platform screenshots, and fees.',
        format: isShorts ? 'TikTok 55s Case Review' : '18min Personal Portfolio Document',
        gapExploited: 'Lack of transparent, verifiable long-term tracking on UK YouTube.',
        targetAudiencePainPoint: 'Uncertainty over whether popular strategies actually work after real fees.',
        viralityPotential: 'Exceptional',
        competitionLevel: 'Low',
        whyItWins: 'Radical transparency converts casual viewers into committed subscribers.',
      },
      {
        title: `Top 5 Free UK Tools & Platforms for ${subject} That Beat Paid Software`,
        angle: 'Essential free calculators, fee visualisers, and research databases.',
        format: isShorts ? 'Reel 45s Tool Tour' : '14min Tool Demo',
        gapExploited: 'Expensive subscriptions marketed to beginners when free alternatives exist.',
        targetAudiencePainPoint: 'Paying £30-£50 monthly for financial tools you don\'t need.',
        viralityPotential: 'Very High',
        competitionLevel: 'Medium',
        whyItWins: 'High utility reference content that drives heavy saving.',
      },
      {
        title: `What to Do When the Market Drops: The UK Survival Guide for ${subject}`,
        angle: 'Downside management, emotional discipline, and pounds-cost averaging.',
        format: isShorts ? 'Shorts 40s Emergency Guide' : '12min Market Volatility Guide',
        gapExploited: 'Panic mongering during downturns rather than pragmatic rebalancing.',
        targetAudiencePainPoint: 'Panic selling at the bottom out of fear of losing everything.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Calm, authoritative reassurance in turbulent market conditions.',
      },
      {
        title: `Stop Copying US Advice: UK Rules for ${subject} That Every Brit Needs to Know`,
        angle: 'Side-by-side contrast between US 401k/Roth IRA terminology and UK ISA/SIPP rules.',
        format: isShorts ? 'Shorts 45s UK vs US' : '13min Cross-Border Audit',
        gapExploited: 'American finance creators dominating UK algorithm feeds with inapplicable rules.',
        targetAudiencePainPoint: 'Trying to apply 401k rules that do not exist under UK HMRC law.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Validates British viewers and establishes domestic authority.',
      },
      {
        title: `How to Automate ${subject} So You Never Miss a Contribution`,
        angle: 'Direct debits, standing orders, and salary sacrifice mechanics.',
        format: isShorts ? 'Reel 40s Setup' : '10min Automation Walkthrough',
        gapExploited: 'Relying on willpower rather than automated wealth architecture.',
        targetAudiencePainPoint: 'Forgetting to invest regularly and spending surplus cash.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Practical implementation with immediate financial benefits.',
      },
      {
        title: `The 80/20 Rule for ${subject}: The 2 Decisions That Determine 80% of Wealth`,
        angle: 'Asset allocation and keeping platform costs under 0.25% vs picking single winners.',
        format: isShorts ? 'TikTok 45s 80/20 Truth' : '11min Principle Walkthrough',
        gapExploited: 'Obsessing over micro-optimisations while ignoring major cost drivers.',
        targetAudiencePainPoint: 'Analysis paralysis over hundreds of fund choices.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Simplifies finance down to what actually drives real results.',
      },
      {
        title: `UK Finance Q&A: Answering the 10 Most Common Questions on ${subject}`,
        angle: 'Direct answers to audience questions on tax allowances, platform safety, and SIPPs.',
        format: isShorts ? 'Reel 50s Rapid Fire Answers' : '15min Community FAQ',
        gapExploited: 'Specific dilemmas that general tutorials skip over.',
        targetAudiencePainPoint: 'Lingering questions holding back the first investment.',
        viralityPotential: 'Medium',
        competitionLevel: 'Low',
        whyItWins: 'Builds deep trust and community loyalty.',
      },
      {
        title: `The UK Due Diligence Checklist for ${subject}: Regulated Platforms & FCA Protection`,
        angle: 'FSCS compensation, FCA registry checks, and avoiding online clones.',
        format: isShorts ? 'Shorts 40s Safety Check' : '12min Due Diligence Guide',
        gapExploited: 'Rising prevalence of sophisticated unregulated scams targeting savers.',
        targetAudiencePainPoint: 'Fear of sending savings to an unauthorised or fraudulent firm.',
        viralityPotential: 'Exceptional',
        competitionLevel: 'Low',
        whyItWins: 'Crucial public safety service that viewers eagerly share with relatives.',
      },
    ];
  }

  // pt-PT finance
  return [
    {
      title: `O Erro no IRS e Comissões em Portugal com ${subject} que Ninguém Te Avisa`,
      angle: 'Alerta regulamentar e fiscal desmistificado com documento real no ecrã.',
      format: isShorts ? 'Shorts 45s com Gancho de Alerta' : 'Vídeo Longo 14min com Ecrã no Portal das Finanças',
      gapExploited: 'Lacuna de fiscalidade portuguesa prática versus conselhos genéricos estrangeiros.',
      targetAudiencePainPoint: 'Medo de cometer erros fiscais e receber coimas surpresa da Autoridade Tributária.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'Ao abrir o portal oficial e mostrar os campos exatos, ganha autoridade instantânea.',
    },
    {
      title: `Como Começar em ${subject} em Portugal com Apenas 50€ a 100€ por Mês`,
      angle: 'Guia ultrarrealista desenhado especificamente para o salário médio nacional.',
      format: isShorts ? 'Reel de 50s em 3 Passos' : 'Vídeo de 12min Passo a Passo com Simulação em Euros',
      gapExploited: 'Inexistência de conteúdos pragmáticos com valores reais acessíveis para jovens portugueses.',
      targetAudiencePainPoint: 'Frustração com criadores que dizem que é preciso ter milhares de euros para começar.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Conecta-se diretamente com a realidade socioeconómica sem paternalismo.',
    },
    {
      title: `Bancos Portugueses Tradicionais vs Novas Opções: Onde Perdes Menos Dinheiro`,
      angle: 'Auditoria implacável de comissões ocultas e preçários públicos comparados.',
      format: isShorts ? 'TikTok 40s com Tabela' : 'Vídeo YouTube 16min Tabela Completa',
      gapExploited: 'Falta de transparência e receio da banca tradicional em Portugal.',
      targetAudiencePainPoint: 'Pagamento de comissões de manutenção de conta e custódia abusivas.',
      viralityPotential: 'Very High',
      competitionLevel: 'Medium',
      whyItWins: 'Gera debate fervoroso na secção de comentários e elevado número de gravações.',
    },
    {
      title: `Por que 90% das Pessoas Falham em ${subject} em Portugal (E o Segredo dos 10%)`,
      angle: 'Quebra de mito e desmontagem do conselho padrão que já não funciona.',
      format: isShorts ? 'Shorts 45s de Choque' : 'Vídeo 15min Análise Crítica',
      gapExploited: 'Saturação de discursos motivacionais vazios.',
      targetAudiencePainPoint: 'Sensação de estar a remar contra a maré sem ver resultados práticos.',
      viralityPotential: 'High',
      competitionLevel: 'Medium',
      whyItWins: 'Ativa a aversão ao erro e curiosidade ao desafiar o senso comum.',
    },
    {
      title: `A Minha Rotina Mensal de 15 Minutos para Gerir ${subject}`,
      angle: 'Minimalismo operacional para quem trabalha a tempo inteiro.',
      format: isShorts ? 'POV Timelapse 35s' : 'Vídeo 10min Walkthrough de Rotina',
      gapExploited: 'Falta de tempo e sobrecarga de informação dos profissionais.',
      targetAudiencePainPoint: 'Não ter horas livres para estudar métodos complexos.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Promessa de resultado com baixo atrito de tempo é o maior íman de retenção.',
    },
    {
      title: `A Regra Não Escrita de IRS e Retenções em Portugal para ${subject}`,
      angle: 'Tributação autónoma de 28% vs englobamento e declaração no Anexo J/G.',
      format: isShorts ? 'Shorts 45s Dica Fiscal' : 'Vídeo 13min Estudo de Caso',
      gapExploited: 'Conteúdo quase sempre cópia de regras fiscais de outros países.',
      targetAudiencePainPoint: 'Dúvidas complexas no preenchimento anual do IRS.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Valor de utilidade pública duradoura para contribuintes portugueses.',
    },
    {
      title: `3 Coisas em ${subject} que Parecem Vantajosas Mas São um Desperdício`,
      angle: 'Contrarian puro: desmontar produtos caros com comissões de gestão abusivas.',
      format: isShorts ? 'Reel de 40s com 3 Cortes' : 'Vídeo 11min Desmistificação',
      gapExploited: 'Ceticismo da audiência perante promessas excessivas dos bancos.',
      targetAudiencePainPoint: 'Cansaço de pagar comissões sem retorno real.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Gera confiança inabalável ao poupar dinheiro real à audiência.',
    },
    {
      title: `Como Estruturar ${subject} do Zero Mesmo Sem Ter Experiência Prévia`,
      angle: 'Passo zero descomplicado com glossário simples em bom português.',
      format: isShorts ? 'Shorts 50s com Checklist' : 'Vídeo 15min Tutorial para Leigos',
      gapExploited: 'A barreira técnica da linguagem rebuscada dos especialistas.',
      targetAudiencePainPoint: 'Medo de parecer ignorante ou não compreender termos financeiros.',
      viralityPotential: 'High',
      competitionLevel: 'Medium',
      whyItWins: 'Acolhe o público principiante que os criadores técnicos ignoram.',
    },
    {
      title: `Testei a Estratégia Mais Famosa de ${subject} por 12 Meses (Resultados Reais)`,
      angle: 'Experimento empírico com diário de bordo e números abertos com comissões deduzidas.',
      format: isShorts ? 'TikTok 55s Formato Story' : 'Vídeo 18min Documentário Pessoal',
      gapExploited: 'Falta de verificação prática e honesta das promessas de mercado.',
      targetAudiencePainPoint: 'Incerteza se as estratégias populares realmente funcionam.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'Storytelling autêntico com prova visual converte espectadores em fãs fiéis.',
    },
    {
      title: `As 5 Ferramentas Gratuitas em Portugal para Acompanhar ${subject}`,
      angle: 'Arsenal gratuito e acessível para simulação e acompanhamento.',
      format: isShorts ? 'Reel 45s Guarda este vídeo' : 'Vídeo 14min Demonstração de Ferramentas',
      gapExploited: 'Falta de conhecimento das ferramentas gratuitas oficiais e calculadoras locais.',
      targetAudiencePainPoint: 'Pagar subscrições caras desnecessárias.',
      viralityPotential: 'Very High',
      competitionLevel: 'Medium',
      whyItWins: 'Formato clássico com elevada taxa de gravação nos favoritos.',
    },
    {
      title: `O Que Fazer em Épocas de Crise ou Queda dos Mercados com ${subject}`,
      angle: 'Psicologia de aversão à perda e protocolo de defesa de capital.',
      format: isShorts ? 'Shorts 40s Resposta de Emergência' : 'Vídeo 13min Gestão de Pânico',
      gapExploited: 'Falta de orientação emocional séria quando o mercado corrige.',
      targetAudiencePainPoint: 'Ansiedade de ver o património temporariamente a descer.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Posiciona o criador como figura de estabilidade e confiança.',
    },
    {
      title: `Pára de Copiar Conselhos Estrangeiros: As Diferenças Cruciais de ${subject} em Portugal`,
      angle: 'Comparativo frontal das diferenças regulatórias entre Portugal e EUA/Brasil.',
      format: isShorts ? 'Shorts 45s Alerta' : 'Vídeo 12min Análise de Fundo',
      gapExploited: 'Dicas copiadas que não se aplicam à nossa legislação.',
      targetAudiencePainPoint: 'Descobrir tarde demais que seguiu conselhos que dão coima em Portugal.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Apelo patriótico e pragmático com forte identificação.',
    },
    {
      title: `Como Automatizar ${subject} para Nunca Mais Precisares de Pensar Nisso`,
      angle: 'Transferências automáticas e protocolos de débito direto.',
      format: isShorts ? 'Reel 35s Setup Rápido' : 'Vídeo 9min Tutorial de Automação',
      gapExploited: 'Depender da força de vontade todos os meses para poupar.',
      targetAudiencePainPoint: 'Chegar ao fim do mês sem conseguir separar o dinheiro pretendido.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Transforma uma decisão difícil num hábito 100% automático.',
    },
    {
      title: `A Regra 80/20 em ${subject}: Onde Realmente Deves Focar a Tua Energia`,
      angle: 'Eliminar o ruído diário das notícias e focar nas 2 decisões essenciais.',
      format: isShorts ? 'TikTok 45s Regra de Ouro' : 'Vídeo 11min Princípios Chave',
      gapExploited: 'Ansiedade com micro-notícias diárias sem impacto real.',
      targetAudiencePainPoint: 'Estar sempre a olhar para aplicações sem necessidade.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Devolve a tranquilidade mental à audiência.',
    },
    {
      title: `Perguntas e Respostas: As 10 Dúvidas Frequentes da Comunidade sobre ${subject}`,
      angle: 'Respostas diretas a casos reais com exemplos numéricos em euros.',
      format: isShorts ? 'Reel 50s Perguntas Rápidas' : 'Vídeo 17min FAQ Especial',
      gapExploited: 'Ignorar as dúvidas reais deixadas nos comentários.',
      targetAudiencePainPoint: 'Ter dúvidas específicas e não encontrar respostas claras.',
      viralityPotential: 'Medium',
      competitionLevel: 'Low',
      whyItWins: 'Gera comunidade e interação calorosa.',
    },
    {
      title: `A Checklist de Segurança e Regulação para ${subject}: Como Evitar Fraudes`,
      angle: 'Verificação na CMVM e Banco de Portugal para não cair em esquemas piramidais.',
      format: isShorts ? 'Shorts 45s Cartão de Alerta' : 'Vídeo 13min Auditoria de Segurança',
      gapExploited: 'Proliferação de burlas no Instagram e WhatsApp a visar o público português.',
      targetAudiencePainPoint: 'Medo legítimo de perder as poupanças em plataformas fraudulentas.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'Serviço público essencial que todo o espectador partilha com familiares.',
    },
  ];
}

function buildGeneralIdeas(subject: string, market: TargetMarket, isShorts: boolean): IdeaTemplateSpec[] {
  const isUK = market === 'en-GB';
  return [
    {
      title: isUK ? `The #1 Mistake with ${subject} (And How to Fix It)` : `O Maior Erro com ${subject} que Pouca Gente Te Avisa`,
      angle: 'Overcoming the most common beginner stumble with clear demonstration.',
      format: isShorts ? 'Shorts 45s Reality Check' : '12min Practical Walkthrough',
      gapExploited: 'Generic advice that glosses over initial setup difficulties.',
      targetAudiencePainPoint: 'Wasting hours without achieving clear progress.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'Direct troubleshooting builds instant credibility.',
    },
    {
      title: isUK ? `How to Master ${subject} from Scratch Step-by-Step` : `Como Dominar ${subject} do Zero Passo a Passo`,
      angle: 'Jargon-free beginner roadmap with clear actionable phases.',
      format: isShorts ? 'Reel 50s 3-Step Blueprint' : '14min Complete Guide',
      gapExploited: 'Theoretical lectures that lack real implementation workflows.',
      targetAudiencePainPoint: 'Not knowing where to start or what tools to choose.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Actionable and empowering for everyday newcomers.',
    },
    {
      title: isUK ? `Tool A vs Tool B for ${subject}: Which Is Genuinely Worth It?` : `Opção A vs Opção B para ${subject}: Qual a Melhor Escolha?`,
      angle: 'Unsponsored objective comparison of the leading market alternatives.',
      format: isShorts ? 'TikTok 40s Comparison' : '15min Honest Audit',
      gapExploited: 'Sponsored influencer reviews promoting products solely for affiliate fees.',
      targetAudiencePainPoint: 'Confusion over which option provides real value.',
      viralityPotential: 'Very High',
      competitionLevel: 'Medium',
      whyItWins: 'Unbiased reviews trigger heavy bookmarking and discussion.',
    },
    {
      title: isUK ? `Why 90% Fail at ${subject} (And the 10% Secret)` : `Por que 90% das Pessoas Desistem de ${subject} (E o Segredo para Ter Sucesso)`,
      angle: 'Identifying the core bottleneck and providing the counter-intuitive workaround.',
      format: isShorts ? 'Shorts 45s Pattern Interrupt' : '12min Strategic Analysis',
      gapExploited: 'Sensationalist promises that ignore execution friction.',
      targetAudiencePainPoint: 'Hitting an early wall and losing motivation.',
      viralityPotential: 'High',
      competitionLevel: 'Medium',
      whyItWins: 'Challenges common assumptions with refreshing honesty.',
    },
    {
      title: isUK ? `The 15-Minute Daily Routine for ${subject}` : `A Rotina Diária de 15 Minutos para Evoluir em ${subject}`,
      angle: 'Low-friction habit stacking designed for busy working schedules.',
      format: isShorts ? 'POV 35s Routine' : '10min Routine Walkthrough',
      gapExploited: 'Overly demanding procedures that lead to rapid burnout.',
      targetAudiencePainPoint: 'Having very little free time outside work commitments.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'High feasibility drives peak save rates.',
    },
    {
      title: isUK ? `The Unwritten Rule of ${subject} That Changes Everything` : `A Regra Não Escrita de ${subject} que Muda os Teus Resultados`,
      angle: 'The insider principle that separates experienced practitioners from novices.',
      format: isShorts ? 'Shorts 40s Quick Tip' : '11min Masterclass',
      gapExploited: 'Textbook guides that leave out practical tricks of the trade.',
      targetAudiencePainPoint: 'Working hard but getting mediocre results.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Specific insider nuance triggers high curiosity.',
    },
    {
      title: isUK ? `3 Things in ${subject} You Should Stop Doing Today` : `3 Hábitos em ${subject} que Deves Parar Hoje`,
      angle: 'Contrarian teardown of outdated advice and wasted effort.',
      format: isShorts ? 'Reel 40s 3 Fast Cuts' : '12min Myth-Buster',
      gapExploited: 'Dogmatic rules copied blindly across internet communities.',
      targetAudiencePainPoint: 'Wasting energy on practices that yield zero tangible benefit.',
      viralityPotential: 'Very High',
      competitionLevel: 'Low',
      whyItWins: 'Provocative contrarian angles generate viral comment debates.',
    },
    {
      title: isUK ? `How to Get Real Results in ${subject} Without Expensive Equipment` : `Como Obter Resultados em ${subject} Sem Gastar uma Fortuna`,
      angle: 'Achieving 90% of the outcome with simple, accessible baseline tools.',
      format: isShorts ? 'Shorts 45s Minimalist Setup' : '13min Budget Blueprint',
      gapExploited: 'The misconception that expensive gear is required to get started.',
      targetAudiencePainPoint: 'Hesitation due to the perceived high cost of entry.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Empowers beginners and dismantles the gatekeeping mentality.',
    },
    {
      title: isUK ? `I Tested the Most Viral Method for ${subject} for 30 Days (Real Review)` : `Testei o Método Mais Famoso de ${subject} Durante 30 Dias (Resultados Reais)`,
      angle: 'Honest empirical test comparing claims vs reality with open records.',
      format: isShorts ? 'TikTok 55s Case Review' : '16min 30-Day Audit',
      gapExploited: 'Unsubstantiated claims by hype-driven creators.',
      targetAudiencePainPoint: 'Uncertainty over which popular method actually works.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'True empirical testing builds bulletproof audience trust.',
    },
    {
      title: isUK ? `The Top 5 Free Resources for ${subject} You Need to Know` : `As 5 Melhores Ferramentas Gratuitas para ${subject}`,
      angle: 'Curated toolkit of high-value free software, templates, and platforms.',
      format: isShorts ? 'Reel 45s Tool Tour' : '14min Free Toolkit Demo',
      gapExploited: 'Expensive subscriptions marketed to newcomers unnecessarily.',
      targetAudiencePainPoint: 'Spending money on tools before validating the concept.',
      viralityPotential: 'Very High',
      competitionLevel: 'Medium',
      whyItWins: 'Immediate bookmark value for learners.',
    },
    {
      title: isUK ? `What to Do When You Get Stuck in ${subject} (Emergency Guide)` : `O Que Fazer Quando Empancas em ${subject} (Guia de Desbloqueio)`,
      angle: 'Rapid diagnostics to pinpoint where things broke down and how to resume.',
      format: isShorts ? 'Shorts 40s Troubleshooting' : '10min Troubleshooting Masterclass',
      gapExploited: 'Guides that offer zero troubleshooting when unexpected errors occur.',
      targetAudiencePainPoint: 'Frustration of getting stuck on an unstated minor detail.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'High-urgency problem solving that gets shared across forums.',
    },
    {
      title: isUK ? `The Modern Approach to ${subject} in 2026` : `A Abordagem Moderna para ${subject} em 2026`,
      angle: 'Contrasting legacy techniques with modern, streamlined workflows.',
      format: isShorts ? 'Shorts 45s Before/After' : '13min Evolution Guide',
      gapExploited: 'Outdated tutorials that ignore modern tools and automations.',
      targetAudiencePainPoint: 'Learning methods that are already obsolete.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Relevance and timeliness drive high click-through rates.',
    },
    {
      title: isUK ? `How to Automate ${subject} So It Takes Almost Zero Effort` : `Como Automatizar ${subject} para Poupar Tempo Toda a Semana`,
      angle: 'Setting up automated systems and shortcuts to handle repetitive tasks.',
      format: isShorts ? 'Reel 35s Setup' : '10min Automation Walkthrough',
      gapExploited: 'Doing repetitive manual work that could easily be automated.',
      targetAudiencePainPoint: 'Spending valuable hours on tedious, repetitive steps.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Time savings are the most universal hook on video platforms.',
    },
    {
      title: isUK ? `The 80/20 Rule in ${subject}: Focus on What Actually Moves the Needle` : `A Regra 80/20 em ${subject}: Foca no Que Realmente Traz Resultados`,
      angle: 'Cutting out 80% of trivial tasks and mastering the 2 vital levers.',
      format: isShorts ? 'TikTok 45s 80/20 Truth' : '11min Principle Walkthrough',
      gapExploited: 'Information overload that paralyses action.',
      targetAudiencePainPoint: 'Feeling overwhelmed by endless options and steps.',
      viralityPotential: 'High',
      competitionLevel: 'Low',
      whyItWins: 'Provides clarity and peace of mind.',
    },
    {
      title: isUK ? `Community Q&A: Answering the 10 Most Common Questions on ${subject}` : `Perguntas e Respostas: As 10 Dúvidas Mais Comuns sobre ${subject}`,
      angle: 'Direct answers to real audience roadblocks with live screen demonstrations.',
      format: isShorts ? 'Reel 50s Rapid Fire Answers' : '15min Community FAQ',
      gapExploited: 'Specific real-world hurdles that generic tutorials skip.',
      targetAudiencePainPoint: 'Unanswered specific questions blocking progress.',
      viralityPotential: 'Medium',
      competitionLevel: 'Low',
      whyItWins: 'Deepens community loyalty and ongoing interaction.',
    },
    {
      title: isUK ? `The Complete Beginner Checklist for ${subject}: Free Saveable Framework` : `A Checklist Completa para ${subject}: Guia Rápido para Guardar`,
      angle: 'Clean visual summary card designed for saving to phone camera rolls.',
      format: isShorts ? 'Shorts 40s Save-to-Phone Checklist' : '10min Summary Walkthrough',
      gapExploited: 'Lack of single-page summary reference assets.',
      targetAudiencePainPoint: 'Forgetting critical steps during execution.',
      viralityPotential: 'Exceptional',
      competitionLevel: 'Low',
      whyItWins: 'Peak bookmark and share rates across social media algorithms.',
    },
  ];
}

export function generateRankedIdeas(
  req: ResearchRequest,
  gaps: ContentGap[],
  competitors: CompetitorResult[]
): ContentIdea[] {
  const { topic, market, platform } = req;
  const isShorts = platform === 'youtube-shorts' || platform === 'tiktok' || platform === 'instagram-reels';
  const topicClean = normalizeTopic(topic, market);
  const domainInfo = detectTopicDomain(topic);

  let rawSpecs: IdeaTemplateSpec[] = [];

  if (domainInfo.isBakingOrCooking) {
    rawSpecs = buildCookingIdeas(domainInfo.primarySubject || topicClean, market, isShorts);
  } else if (domainInfo.isGardening) {
    rawSpecs = buildGardeningIdeas(domainInfo.primarySubject || topicClean, market, isShorts);
  } else if (domainInfo.isHealthOrFitness) {
    rawSpecs = buildHealthIdeas(domainInfo.primarySubject || topicClean, market, isShorts);
  } else if (domainInfo.isConsumerBudgeting) {
    rawSpecs = buildConsumerBudgetingIdeas(domainInfo.primarySubject || topicClean, market, isShorts);
  } else if (domainInfo.isFinance) {
    rawSpecs = buildFinanceIdeas(domainInfo.primarySubject || topicClean, market, isShorts);
  } else {
    rawSpecs = buildGeneralIdeas(domainInfo.primarySubject || topicClean, market, isShorts);
  }

  // Calculate Opportunity Score (0-100) using transparent formula:
  // Demand (0-35) + Competitor Gap (0-35) + Virality / Pacing (0-30)
  const ranked: ContentIdea[] = rawSpecs.map((spec, index) => {
    let demandScore = 32 - Math.floor(index * 0.9);
    let gapScore = spec.competitionLevel === 'Low' ? 34 : spec.competitionLevel === 'Medium' ? 29 : 23;
    let viralityScore = spec.viralityPotential === 'Exceptional' ? 29 : spec.viralityPotential === 'Very High' ? 25 : 20;

    let totalScore = Math.min(99, Math.max(70, demandScore + gapScore + viralityScore - (index % 3)));

    return {
      id: `idea-${market.toLowerCase()}-${index + 1}`,
      title: cleanTemplateText(spec.title),
      angle: spec.angle,
      format: spec.format,
      gapExploited: spec.gapExploited,
      targetAudiencePainPoint: spec.targetAudiencePainPoint,
      viralityPotential: spec.viralityPotential === 'Medium' ? 'High' : spec.viralityPotential,
      competitionLevel: spec.competitionLevel,
      rank: index + 1,
      opportunityScore: totalScore,
      whyItWins: spec.whyItWins,
      isBestOpportunity: index === 0,
    };
  });

  // Sort descending by opportunity score
  ranked.sort((a, b) => b.opportunityScore - a.opportunityScore);

  // Re-assign ranks 1 to N after sort and ensure #1 is best opportunity
  ranked.forEach((item, idx) => {
    item.rank = idx + 1;
    item.isBestOpportunity = idx === 0;
  });

  return ranked;
}
