import { ContentIdea, ResearchRequest, ContentGap, CompetitorResult } from '../../src/types/index.js';

export function generateRankedIdeas(
  req: ResearchRequest,
  gaps: ContentGap[],
  competitors: CompetitorResult[]
): ContentIdea[] {
  const { topic, market, platform } = req;
  const isShorts = platform === 'youtube-shorts' || platform === 'tiktok' || platform === 'instagram-reels';

  const rawIdeas: Omit<ContentIdea, 'rank' | 'opportunityScore' | 'isBestOpportunity'>[] = [];

  if (market === 'pt-PT') {
    rawIdeas.push(
      {
        id: 'idea-pt-1',
        title: `O Erro no IRS / Custos em Portugal com ${topic} que Ninguém Te Avisa`,
        angle: 'Alerta regulamentar e fiscal desmistificado com documento real no ecrã.',
        format: isShorts ? 'Shorts/Reels 45s com Gancho de Quebra de Padrão' : 'Vídeo Longo 14min com Gravação de Ecrã no Portal das Finanças',
        gapExploited: 'Lacuna de fiscalidade portuguesa prática versus conselhos genéricos estrangeiros.',
        targetAudiencePainPoint: 'Medo de cometer erros fiscais e receber coimas surpresa da Autoridade Tributária.',
        viralityPotential: 'Exceptional',
        competitionLevel: 'Low',
        whyItWins: 'A maioria dos canais só ensina teorias. Ao abrir o portal oficial e mostrar os campos exatos, ganha autoridade instantânea e taxa máxima de partilha.',
      },
      {
        id: 'idea-pt-2',
        title: `Como Começar em ${topic} em Portugal com Apenas 50€ a 100€ por Mês`,
        angle: 'Guia ultrarrealista desenhado especificamente para o salário médio nacional.',
        format: isShorts ? 'Reel de 50s em 3 Passos Práticos' : 'Vídeo de 12min Passo a Passo com Simulação em Euros',
        gapExploited: 'Inexistência de conteúdos pragmáticos com valores reais acessíveis para jovens portugueses.',
        targetAudiencePainPoint: 'Frustração com criadores que dizem que é preciso ter milhares de euros para começar.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Conecta-se diretamente com a realidade socioeconómica de Lisboa, Porto e restante país sem paternalismo.',
      },
      {
        id: 'idea-pt-3',
        title: `Bancos Portugueses Tradicionais vs Novas Opções: Onde Perdes Menos Dinheiro`,
        angle: 'Auditoria implacável de comissões ocultas e preçários públicos comparados.',
        format: isShorts ? 'TikTok/Reels 40s com Tabela Comparativa' : 'Vídeo YouTube 16min Tabela Excel Completa',
        gapExploited: 'Falta de transparência e receio da banca tradicional em Portugal.',
        targetAudiencePainPoint: 'Pagamento de comissões de manutenção de conta e custódia abusivas.',
        viralityPotential: 'Very High',
        competitionLevel: 'Medium',
        whyItWins: 'Gera debate fervoroso na secção de comentários e elevado número de gravações nos favoritos.',
      },
      {
        id: 'idea-pt-4',
        title: `Por que 90% das Pessoas Falham em ${topic} em Portugal (E o Segredo dos 10%)`,
        angle: 'Quebra de mito e desmontagem do conselho padrão que já não funciona em 2025/2026.',
        format: isShorts ? 'Shorts 45s de Choque de Realidade' : 'Vídeo 15min Análise Crítica',
        gapExploited: 'Saturação de discursos motivacionais vazios.',
        targetAudiencePainPoint: 'Sensação de estar a remar contra a maré sem ver resultados práticos.',
        viralityPotential: 'High',
        competitionLevel: 'Medium',
        whyItWins: 'Ativa a aversão ao erro e curiosidade ao desafiar o senso comum.',
      },
      {
        id: 'idea-pt-5',
        title: `A Minha Rotina Semanal de 15 Minutos para Dominar ${topic}`,
        angle: 'Minimalismo operacional para quem trabalha a tempo inteiro.',
        format: isShorts ? 'POV Timelapse 35s com Narração' : 'Vídeo 10min Walkthrough de Rotina',
        gapExploited: 'Falta de tempo e sobrecarga de informação dos profissionais.',
        targetAudiencePainPoint: 'Não ter horas livres para estudar métodos complexos.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Promessa de resultado com baixo atrito de tempo é o maior ímã de retenção.',
      },
      {
        id: 'idea-pt-6',
        title: `O Guia Definitivo de ${topic} para Quem Vive Fora dos Grandes Centros em Portugal`,
        angle: 'Interior de Portugal e zonas periféricas: oportunidades e particularidades.',
        format: isShorts ? 'Shorts 45s Focado em Descentralização' : 'Vídeo 13min Estudo de Caso',
        gapExploited: 'Conteúdo quase 100% focado apenas na bolha de Lisboa.',
        targetAudiencePainPoint: 'Dificuldade em aplicar estratégias em cidades médias e pequenas.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Audiência fora das capitais sente-se representada e defende o criador.',
      },
      {
        id: 'idea-pt-7',
        title: `3 Coisas em ${topic} que Parecem Vantajosas Mas São um Desperdício`,
        angle: 'Contrarian puro: desmontar três produtos ou métodos populares vendidos na internet.',
        format: isShorts ? 'Reel de 40s com 3 Cortes Rápidos' : 'Vídeo 11min Desmistificação',
        gapExploited: 'Ceticismo da audiência perante promessas excessivas.',
        targetAudiencePainPoint: 'Cansaço de cair em armadilhas de marketing digital ou cursos vazios.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Gera confiança inabalável ao poupar dinheiro real à audiência.',
      },
      {
        id: 'idea-pt-8',
        title: `Como Estruturar ${topic} do Zero Mesmo Sem Ter Experiência Prévia`,
        angle: 'Passo zero descomplicado com glossário simples em bom português.',
        format: isShorts ? 'Shorts 50s com Checklist no Ecrã' : 'Vídeo 15min Tutorial para Leigos',
        gapExploited: 'A barreira técnica da linguagem rebuscada dos especialistas.',
        targetAudiencePainPoint: 'Medo de parecer ignorante ou não compreender termos em inglês.',
        viralityPotential: 'High',
        competitionLevel: 'Medium',
        whyItWins: 'Acolhe o público principiante que os criadores técnicos ignoram.',
      },
      {
        id: 'idea-pt-9',
        title: `Testei a Estratégia Mais Famosa de ${topic} por 60 Dias (Resultados Reais)`,
        angle: 'Experimento empírico com diário de bordo e números abertos.',
        format: isShorts ? 'TikTok 55s Formato Diário/Story' : 'Vídeo 18min Documentário Pessoal',
        gapExploited: 'Falta de verificação prática e honesta das promessas de mercado.',
        targetAudiencePainPoint: 'Incerteza se as estratégias populares realmente funcionam.',
        viralityPotential: 'Exceptional',
        competitionLevel: 'Low',
        whyItWins: 'Storytelling autêntico com prova visual converte espectadores em fãs fiéis.',
      },
      {
        id: 'idea-pt-10',
        title: `As 5 Ferramentas Gratuitas em Portugal que Substituem Software de Centenas de Euros`,
        angle: 'Arsenal gratuito e acessível para obter resultados imediatos em ${topic}.',
        format: isShorts ? 'Reel 45s "Salva este vídeo"' : 'Vídeo 14min Demonstração de Ferramentas',
        gapExploited: 'Custo de entrada proibitivo das ferramentas recomendadas por gurus.',
        targetAudiencePainPoint: 'Falta de capital para investir em subscrições de software caro.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Ímã de partilhas e salvamentos por entregar utilidade prática instantânea.',
      },
      {
        id: 'idea-pt-11',
        title: `O que Mudou em ${topic} em 2025/2026: O Que Deves Fazer Ainda Hoje`,
        angle: 'Atualização de timing e antecipação de tendências.',
        format: isShorts ? 'Shorts 40s Alerta Noticioso' : 'Vídeo 12min Análise de Tendências',
        gapExploited: 'Conteúdos antigos desatualizados que induzem em erro.',
        targetAudiencePainPoint: 'Incerteza perante novidades e alterações legais/técnicas.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'O gatilho da novidade e urgência acelera as visualizações orgânicas.',
      },
      {
        id: 'idea-pt-12',
        title: `Auditoria em Direto: Analisando Casos Reais de ${topic} em Portugal`,
        angle: 'Análise de casos submetidos por seguidores com diagnóstico honesto.',
        format: isShorts ? 'TikTok 50s Reação / Análise' : 'Vídeo 16min Consultoria Prática',
        gapExploited: 'Distância entre teoria e aplicação em casos particulares.',
        targetAudiencePainPoint: 'Não saber identificar os próprios pontos cegos.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Interatividade e identificação imediata com os erros de outros utilizadores.',
      },
      {
        id: 'idea-pt-13',
        title: `Como Automatizar 80% do Teu Trabalho em ${topic} com Processos Simples`,
        angle: 'Eficiência sem necessidade de conhecimentos de programação.',
        format: isShorts ? 'Reel 40s Fluxo de Ecrã' : 'Vídeo 13min Tutorial de Automação',
        gapExploited: 'Perda de tempo em tarefas repetitivas e manuais.',
        targetAudiencePainPoint: 'Esgotamento e falta de tempo para focar na estratégia.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Apelo direto à produtividade e alívio do stress diário.',
      },
      {
        id: 'idea-pt-14',
        title: `A Verdade Sobre Certificações e Diplomas em ${topic}: Vale a Pena Investir?`,
        angle: 'Análise fria de custo-benefício de cursos e certificados formais.',
        format: isShorts ? 'Shorts 45s Opinião Direta' : 'Vídeo 12min Avaliação de Mercado',
        gapExploited: 'Indústria predatória de cursos de formação que prometem carreiras fáceis.',
        targetAudiencePainPoint: 'Dúvida se deve gastar milhares de euros em formações académicas.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Protege o dinheiro da audiência e atrai comentários apaixonados.',
      },
      {
        id: 'idea-pt-15',
        title: `Como Negociar Melhores Condições e Poupar em ${topic} com 3 Perguntas`,
        angle: 'Scripts de negociação direta para utilizar com empresas e prestadores.',
        format: isShorts ? 'Reel 45s Roleplay / Diálogo' : 'Vídeo 11min Estratégia de Negociação',
        gapExploited: 'Timidez e falta de técnicas de negociação do público português.',
        targetAudiencePainPoint: 'Aceitar propostas desfavoráveis por vergonha de contrapropor.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Formato teatral e de diálogo tem altíssima taxa de conclusão de vídeo.',
      },
      {
        id: 'idea-pt-16',
        title: `O Checklist de Segurança em ${topic}: Como Evitar Ser Burlado Online`,
        angle: 'Defesa e cibersegurança prática para utilizadores em Portugal.',
        format: isShorts ? 'Shorts 40s Alerta de Burlas' : 'Vídeo 14min Guia Anti-Fraude',
        gapExploited: 'Aumento expressivo de fraudes online e esquemas no mercado português.',
        targetAudiencePainPoint: 'Medo constante de clicar no sítio errado e perder património.',
        viralityPotential: 'Exceptional',
        competitionLevel: 'Low',
        whyItWins: 'O instinto de proteção familiar gera partilhas em massa por WhatsApp.',
      }
    );
  } else if (market === 'pt-BR') {
    rawIdeas.push(
      {
        id: 'idea-br-1',
        title: `A Cilada Oculta em ${topic} que o Seu Banco / Especialista Esconde de Você`,
        angle: 'Denúncia e choque de realidade com cálculo na ponta do lápis sem enrolação.',
        format: isShorts ? 'Shorts/TikTok 45s de Alta Energia' : 'Vídeo YouTube 15min Planilha Comparativa Aberta',
        gapExploited: 'Saturação de vídeos patrocinados e dicas enviesadas de influenciadores.',
        targetAudiencePainPoint: 'Sentimento de estar sendo passado para trás por instituições financeiras.',
        viralityPotential: 'Exceptional',
        competitionLevel: 'Low',
        whyItWins: 'O gatilho da quebra da conspiração/verdade revelada gera retenção estratosférica no Brasil.',
      },
      {
        id: 'idea-br-2',
        title: `Como Dominar ${topic} Começando com Menos de R$ 50 Reais na Prática`,
        angle: 'Acessibilidade radical sem gourmetização de termos.',
        format: isShorts ? 'Reels 45s Gravando a Tela do Celular' : 'Vídeo 12min Passo a Passo para Iniciantes',
        gapExploited: 'Afastamento de mais de 70% da população que ganha até 2 salários mínimos.',
        targetAudiencePainPoint: 'Achar que o tema é apenas para pessoas ricas ou com pós-graduação.',
        viralityPotential: 'Exceptional',
        competitionLevel: 'Medium',
        whyItWins: 'Desmistifica a barreira de entrada e gera conexão empática imediata.',
      },
      {
        id: 'idea-br-3',
        title: `3 Hábitos Simples em ${topic} que Mudam Seus Resultados em 30 Dias`,
        angle: 'Desafio prático focado em microvitórias diárias.',
        format: isShorts ? 'TikTok 40s Dinâmico' : 'Vídeo 11min Estrutura de Hábitos',
        gapExploited: 'Excesso de teorias longas sem aplicação na rotina agitada brasileira.',
        targetAudiencePainPoint: 'Falta de disciplina e sensação de sobrecarga mental.',
        viralityPotential: 'Very High',
        competitionLevel: 'Medium',
        whyItWins: 'Promessa de prazo tangível (30 dias) atrai quem busca mudanças rápidas.',
      },
      {
        id: 'idea-br-4',
        title: `O Comparativo Real: Opção A vs Opção B em ${topic} (Sem Patrocínio)`,
        angle: 'Duelo honesto com prós, contras e letras miúdas.',
        format: isShorts ? 'Shorts 50s Comparativo com Selos' : 'Vídeo 16min Batalha Completa',
        gapExploited: 'Vídeos concorrentes comprados que não apontam os defeitos das marcas.',
        targetAudiencePainPoint: 'Incerteza na hora de escolher qual serviço ou ferramenta assinar.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'A isenção e imparcialidade geram credibilidade vitalícia no canal.',
      },
      {
        id: 'idea-br-5',
        title: `Pare de Fazer Isso em ${topic}! Você Está Queimando Tempo e Dinheiro`,
        angle: 'Interrupção de padrão acusatória bem-humorada com correção imediata.',
        format: isShorts ? 'Reels 35s com Corte Rápido' : 'Vídeo 10min 5 Erros Fatais',
        gapExploited: 'Repetição cega de costumes ultrapassados que todo mundo copia.',
        targetAudiencePainPoint: 'Trabalhar muito e não ver o progresso proporcional.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Forte gatilho de aversão à perda nos primeiros 2 segundos.',
      },
      {
        id: 'idea-br-6',
        title: `Como Organizar ${topic} Dedicando Apenas 10 Minutos no Celular`,
        angle: 'Otimização móvel e sem burocracia para quem passa horas no trânsito.',
        format: isShorts ? 'TikTok 45s Tela do Celular' : 'Vídeo 12min Setup no Smartphone',
        gapExploited: 'Criadores que ensinam usando computadores caros ignorando o celular.',
        targetAudiencePainPoint: 'Não ter computador próprio ou tempo em casa para sentar.',
        viralityPotential: 'Exceptional',
        competitionLevel: 'Low',
        whyItWins: 'O Brasil é prioritariamente mobile-first; falar de celular dobra o alcance.',
      },
      {
        id: 'idea-br-7',
        title: `O Golpe / Armadilha em ${topic} que Mais Está Fazendo Vítimas Hoje`,
        angle: 'Prestação de serviço de proteção contra estelionatos modernos.',
        format: isShorts ? 'Shorts 40s Alerta Vermelho' : 'Vídeo 14min Dossiê Investigativo',
        gapExploited: 'Crescimento de golpes via WhatsApp e Instagram no nicho.',
        targetAudiencePainPoint: 'Medo de perder economias guardadas a custo de muito esforço.',
        viralityPotential: 'Exceptional',
        competitionLevel: 'Low',
        whyItWins: 'Gera distribuição massiva em grupos de família e redes sociais.',
      },
      {
        id: 'idea-br-8',
        title: `Como Eu Começaria ${topic} do Zero se Perdesse Tudo Hoje`,
        angle: 'Plano de emergência e recomeço com base na experiência adquirida.',
        format: isShorts ? 'Reels 50s Storytelling Emocional' : 'Vídeo 17min Plano de Contingência',
        gapExploited: 'Vídeos que só mostram o topo da montanha e esquecem a subida difícil.',
        targetAudiencePainPoint: 'Desespero ou estagnação após uma falha ou recomeço.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Altíssima conexão humana e demonstração de resiliência sem soberba.',
      },
      {
        id: 'idea-br-9',
        title: `3 Ferramentas Gratuitas que Deixam Qualquer Um Profissional em ${topic}`,
        angle: 'Curadoria de ouro sem cobrança de assinatura.',
        format: isShorts ? 'Shorts 45s Lista de Salvamento' : 'Vídeo 13min Tutorial Prático',
        gapExploited: 'Indicação recorrente de softwares gringos cobrados em dólar.',
        targetAudiencePainPoint: 'Falta de verba para bancar ferramentas com conversão do dólar.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Valor percebido imediato com gatilho de reciprocidade.',
      },
      {
        id: 'idea-br-10',
        title: `A Regra dos 80/20 em ${topic}: O Que Realmente Traz 80% do Retorno`,
        angle: 'Corte radical de tarefas inúteis para foco no que gera resultado.',
        format: isShorts ? 'TikTok 40s Quadro Branco' : 'Vídeo 12min Princípio de Pareto',
        gapExploited: 'Overthinking e paralisia por análise dos iniciantes.',
        targetAudiencePainPoint: 'Fazer dezenas de coisas ao mesmo tempo e continuar sem tração.',
        viralityPotential: 'High',
        competitionLevel: 'Medium',
        whyItWins: 'Entrega clareza e alívio mental com simplicidade.',
      },
      {
        id: 'idea-br-11',
        title: `O Manual Secreto de ${topic} que Ninguém Quer que Você Descubra`,
        angle: 'Revelação de estratégias de bastidores usadas pelos grandes players.',
        format: isShorts ? 'Reels 45s Tom Misterioso' : 'Vídeo 15min Análise Tática',
        gapExploited: 'Guardar segredo de métodos eficazes em cursos de milhares de reais.',
        targetAudiencePainPoint: 'Sensação de que existe uma barreira invisível para o sucesso.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'A curiosidade insaciável de conhecer os bastidores sem filtros.',
      },
      {
        id: 'idea-br-12',
        title: `Avaliando Perfis e Dúvidas Reais de Seguidores em ${topic}`,
        angle: 'Consultoria rápida e dinâmica corrigindo falhas ao vivo.',
        format: isShorts ? 'Shorts 50s Reação / Roast Construtivo' : 'Vídeo 18min Análise Coletiva',
        gapExploited: 'Falta de feedback prático e personalizado para dúvidas comuns.',
        targetAudiencePainPoint: 'Estar travado em uma dúvida pontual sem ninguém para responder.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Promove senso de comunidade e gera centenas de comentários solicitando análise.',
      },
      {
        id: 'idea-br-13',
        title: `Como Não Ser Enganado Pelas Novidades de IA e Tendências em ${topic}`,
        angle: 'Filtro de bom senso contra o hype desmedido das novas ferramentas.',
        format: isShorts ? 'TikTok 45s Desmistificação' : 'Vídeo 14min Teste de Eficácia Real',
        gapExploited: 'Cansaço do público com promessas diárias de que a IA vai resolver tudo.',
        targetAudiencePainPoint: 'Ansiedade de FOMO achando que está ficando para trás toda semana.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Equilíbrio e sobriedade geram admiração em um mar de criadores desesperados por views.',
      },
      {
        id: 'idea-br-14',
        title: `A Matemática Sem Mentiras: Quanto Custa de Verdade Começar em ${topic}`,
        angle: 'Tabela de custos ocultos que nenhum curso mostra na página de vendas.',
        format: isShorts ? 'Shorts 40s Matemática Rápida' : 'Vídeo 11min Planilha Aberta',
        gapExploited: 'Surpresa negativa com custos imprevistos após iniciar no mercado.',
        targetAudiencePainPoint: 'Começar algo e desistir no meio do caminho por falta de fluxo de caixa.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Transparência financeira radical atrai os seguidores mais leais e qualificados.',
      },
      {
        id: 'idea-br-15',
        title: `O Método Simples para Manter a Constância em ${topic} Sem Pirar`,
        angle: 'Gestão de energia e hábitos sustentáveis a longo prazo.',
        format: isShorts ? 'Reels 40s Reflexão Prática' : 'Vídeo 12min Protocolo de Sustentabilidade',
        gapExploited: 'Burnout frequente por cobrança de metas inalcançáveis no ambiente digital.',
        targetAudiencePainPoint: 'Começar com todo gás e desistir após 2 ou 3 semanas.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Toca na ferida humana da consistência com compaixão e método aplicável.',
      },
      {
        id: 'idea-br-16',
        title: `Checklist Rápido de 5 Minutos Antes de Tomar Qualquer Decisão em ${topic}`,
        angle: 'Protocolo de segurança mental contra impulsividade.',
        format: isShorts ? 'Shorts 45s Formato Cartão de Bolso' : 'Vídeo 10min Árvore de Decisão',
        gapExploited: 'Decisões tomadas no calor do momento que geram arrependimento.',
        targetAudiencePainPoint: 'Agir por impulso e perder tempo ou dinheiro.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Utilidade imediata que as pessoas salvam no aplicativo para consultar depois.',
      }
    );
  } else {
    // es-ES
    rawIdeas.push(
      {
        id: 'idea-es-1',
        title: `La Trampa Fiscal en España con ${topic} que Tu Gestor Aún No te Ha Contado`,
        angle: 'Auditoría fiscal crítica y soluciones legales contrastadas en la normativa española.',
        format: isShorts ? 'Shorts/Reels 45s con Normativa en Pantalla' : 'Vídeo YouTube 15min Análisis BOE y Caso Real',
        gapExploited: 'Desconocimiento de deducciones y riesgos en la liquidación de impuestos en España.',
        targetAudiencePainPoint: 'Miedo a inspecciones de Hacienda y pago excesivo e injustificado de impuestos.',
        viralityPotential: 'Exceptional',
        competitionLevel: 'Low',
        whyItWins: 'Toca el dolor más sensible en España con rigor legal y números netos verificables.',
      },
      {
        id: 'idea-es-2',
        title: `Cómo Optimizar ${topic} en España Paso a Paso (Sin Humo Ni Promesas Falsas)`,
        angle: 'Enfoque pragmático sin retórica vacía para profesionales y emprendedores.',
        format: isShorts ? 'Reels 50s en 3 Claves Ejecutables' : 'Vídeo 14min Tutorial con Plantilla Descargable',
        gapExploited: 'Cansancio generalizado de conferenciantes teóricos sin experiencia de campo.',
        targetAudiencePainPoint: 'Perder semanas intentando descifrar cómo empezar correctamente.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'El público español valora la honestidad directa y el desprecio por el postureo.',
      },
      {
        id: 'idea-es-3',
        title: `Comparativa Real de Plataformas en España para ${topic}: Dónde se Pierde Menos`,
        angle: 'Duelo de comisiones, facilidad de uso y atención al cliente en España.',
        format: isShorts ? 'TikTok 45s Tabla Comparativa' : 'Vídeo 16min Desglose con Cifras Netas',
        gapExploited: 'Contenidos patrocinados que ocultan las comisiones de retirada y custodia.',
        targetAudiencePainPoint: 'Contratar servicios caros por falta de análisis comparativo independiente.',
        viralityPotential: 'Very High',
        competitionLevel: 'Medium',
        whyItWins: 'Funciona como consulta de referencia y genera decenas de menciones en foros y grupos.',
      },
      {
        id: 'idea-es-4',
        title: `Por Qué el 90% Fracasa en ${topic} en España y Cómo Evitar Formar Parte de Ellos`,
        angle: 'Autopsia de errores comunes del mercado español y protocolo de blindaje.',
        format: isShorts ? 'Shorts 40s Gancho Anti-Fracaso' : 'Vídeo 13min Desglose Estratégico',
        gapExploited: 'Sobreoptimismo falso promovido en redes sociales sin soporte real.',
        targetAudiencePainPoint: 'Frustración tras meses de esfuerzo sin tracción económica.',
        viralityPotential: 'High',
        competitionLevel: 'Medium',
        whyItWins: 'El choque de realidad genera credibilidad inmediata y retención profunda.',
      },
      {
        id: 'idea-es-5',
        title: `Los 3 Gastos en ${topic} que Puedes Deducir Legalmente y Casi Nadie Conoce`,
        angle: 'Optimización de gastos afectos a la actividad con base jurídica sólida.',
        format: isShorts ? 'Reels 45s Formato Lista Secreta' : 'Vídeo 12min Guía de Gastos Deducibles',
        gapExploited: 'Gestorías tradicionales que por comodidad no aplican deducciones permitidas.',
        targetAudiencePainPoint: 'Sentir que se pagan más impuestos de los estrictamente debidos.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Impacto directo en el bolsillo del espectador: es el contenido más guardado.',
      },
      {
        id: 'idea-es-6',
        title: `Cómo Compaginar ${topic} con un Trabajo por Cuenta Ajena en España`,
        angle: 'Pluriactividad, fiscalidad compartida y conciliación sin riesgos contractuales.',
        format: isShorts ? 'TikTok 50s Resumen de Pluriactividad' : 'Vídeo 15min Marco Laboral y Práctico',
        gapExploited: 'Casi todo el contenido asume que se vive 100% de la actividad o de nómina fija.',
        targetAudiencePainPoint: 'Miedo a incompatibilidades laborales con el contrato de trabajo actual.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Responde a una necesidad masiva desatendida por los creadores habituales.',
      },
      {
        id: 'idea-es-7',
        title: `Las 4 Herramientas Gratuitas que Todo Profesional de ${topic} Debería Usar`,
        angle: 'Alternativas de software libre y aplicaciones sin coste para empezar.',
        format: isShorts ? 'Shorts 45s "Guarda este vídeo"' : 'Vídeo 13min Demostración de Software',
        gapExploited: 'Presión por contratar herramientas costosas antes de facturar.',
        targetAudiencePainPoint: 'Falta de presupuesto para herramientas profesionales caras.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Genera máxima reciprocidad y alta ratio de guardados en favoritos.',
      },
      {
        id: 'idea-es-8',
        title: `Mi Rutina Mínima Viable de 20 Minutos al Día en ${topic}`,
        angle: 'Productividad sin fricción para personas con poco tiempo disponible.',
        format: isShorts ? 'Reels 40s Timelapse con Audio Ágil' : 'Vídeo 11min Planificación Semanal',
        gapExploited: 'Saturación de agendas imposibles de cumplir en el día a día.',
        targetAudiencePainPoint: 'Falta de constancia por fatiga y saturación laboral.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'La promesa de bajo tiempo con resultado consistente triunfa en plataformas de vídeo.',
      },
      {
        id: 'idea-es-9',
        title: `Desmontando los 3 Mitos Más Peligrosos sobre ${topic} que Circulan en TikTok`,
        angle: 'Caza de bulos con datos empíricos y verificación de fuentes.',
        format: isShorts ? 'TikTok 50s Reacción a Vídeo Viral' : 'Vídeo 14min Análisis Desmitificador',
        gapExploited: 'Proliferación de consejos absurdos de creadores sin cualificación.',
        targetAudiencePainPoint: 'Confusión ante tanta información contradictoria en redes.',
        viralityPotential: 'Exceptional',
        competitionLevel: 'Low',
        whyItWins: 'El formato de debate y desmontaje de bulos polariza y dispara el algoritmo.',
      },
      {
        id: 'idea-es-10',
        title: `Qué Haría si Tuviera que Volver a Empezar en ${topic} en 2025/2026`,
        angle: 'Hoja de ruta simplificada eliminando todos los errores cometidos en el pasado.',
        format: isShorts ? 'Shorts 50s Storytelling Cercano' : 'Vídeo 16min Hoja de Ruta de Reinicio',
        gapExploited: 'Falta de perspectiva honesta de creadores experimentados.',
        targetAudiencePainPoint: 'Estar al inicio del camino y sentirse abrumado ante tantas opciones.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'Crea una fuerte relación de confianza y fidelidad a largo plazo con la marca.',
      },
      {
        id: 'idea-es-11',
        title: `El Protocolo Anti-Estafas en ${topic}: Cómo Detectar Vendedores de Humo`,
        angle: 'Guía de defensa y preguntas trampa para desenmascarar falsos gurús.',
        format: isShorts ? 'Reels 45s "Las 3 Señales de Alarma"' : 'Vídeo 15min Análisis Forense de Promesas',
        gapExploited: 'Aparición constante de cursos y servicios con promesas irreales en España.',
        targetAudiencePainPoint: 'Miedo a ser engañado y perder dinero en formación inútil.',
        viralityPotential: 'Exceptional',
        competitionLevel: 'Low',
        whyItWins: 'Conecta con la indignación social y se comparte activamente en comunidades.',
      },
      {
        id: 'idea-es-12',
        title: `Automatizaciones Sencillas que Ahorran 5 Horas a la Semana en ${topic}`,
        angle: 'Optimización de flujos de trabajo sin código ni tecnicismos.',
        format: isShorts ? 'Shorts 40s Demostración en Pantalla' : 'Vídeo 13min Configuración Paso a Paso',
        gapExploited: 'Procesos manuales ineficientes que agotan al profesional independiente.',
        targetAudiencePainPoint: 'Sentir que se pasan horas apagando fuegos en vez de avanzar.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Ahorro de tiempo tangible con satisfacción instantánea.',
      },
      {
        id: 'idea-es-13',
        title: `Cuánto Dinero Hace Falta Realmente para Ver Resultados en ${topic}`,
        angle: 'Desglose sin tapujos del presupuesto inicial y recurrente necesario.',
        format: isShorts ? 'TikTok 40s Con Números en Mano' : 'Vídeo 12min Presupuesto Real Auditado',
        gapExploited: 'Ocultación sistemática de los costes de mantenimiento y entrada.',
        targetAudiencePainPoint: 'Sorpresas económicas desagradables después de haber empezado.',
        viralityPotential: 'Very High',
        competitionLevel: 'Low',
        whyItWins: 'La transparencia financiera radical es el mayor generador de lealtad en España.',
      },
      {
        id: 'idea-es-14',
        title: `Cómo Negociar Condiciones Inmejorables en ${topic} Usando Esta Frase`,
        angle: 'Estrategia de asertividad y psicología de negociación práctica.',
        format: isShorts ? 'Reels 45s Simulación de Conversación' : 'Vídeo 11min Tácticas de Negociación',
        gapExploited: 'Falta de preparación para negociar con clientes o proveedores.',
        targetAudiencePainPoint: 'Cobrar de menos o aceptar condiciones desfavorables por pudor.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'El formato de diálogo teatralizado atrapa la atención hasta el último segundo.',
      },
      {
        id: 'idea-es-15',
        title: `Checklist Rápido de 3 Pasos Antes de Firmar Cualquier Acuerdo en ${topic}`,
        angle: 'Blindaje jurídico y operativo en minutos.',
        format: isShorts ? 'Shorts 40s Puntos Clave' : 'Vídeo 10min Revisión de Contratos',
        gapExploited: 'Letra pequeña de acuerdos y servicios que luego atrapa al usuario.',
        targetAudiencePainPoint: 'Firmar condiciones con permanencias o penalizaciones ocultas.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'Utilidad preventiva indispensable con alto índice de descargas y guardados.',
      },
      {
        id: 'idea-es-16',
        title: `Las Novedades de ${topic} que Tienes que Saber Sí o Sí para Este Año`,
        angle: 'Actualización express de cambios de mercado y regulatorios.',
        format: isShorts ? 'TikTok 45s Noticias Críticas' : 'Vídeo 14min Resumen Ejecutivo',
        gapExploited: 'Vídeos desfasados con recomendaciones obsoletas que dañan resultados.',
        targetAudiencePainPoint: 'Quedarse obsoleto o perder oportunidades por desconocimiento.',
        viralityPotential: 'High',
        competitionLevel: 'Low',
        whyItWins: 'El sentido de anticipación posiciona al creador como referente indiscutible.',
      }
    );
  }

  // Calculate Opportunity Score (0-100) using transparent formula:
  // Demand (0-35) + Competitor Gap (0-35) + Virality / Pacing (0-30)
  const ranked: ContentIdea[] = rawIdeas.map((idea, index) => {
    let demandScore = 32 - Math.floor(index * 0.9);
    let gapScore = idea.competitionLevel === 'Low' ? 34 : idea.competitionLevel === 'Medium' ? 29 : 23;
    let viralityScore = idea.viralityPotential === 'Exceptional' ? 29 : idea.viralityPotential === 'Very High' ? 25 : 20;

    let totalScore = Math.min(99, Math.max(70, demandScore + gapScore + viralityScore - (index % 3)));

    return {
      ...idea,
      rank: index + 1,
      opportunityScore: totalScore,
      isBestOpportunity: index === 0,
    };
  });

  // Sort descending by opportunity score
  ranked.sort((a, b) => b.opportunityScore - a.opportunityScore);

  // Re-assign ranks 1 to N after sort and ensure #1 is best opportunity
  ranked.forEach((item, idx) => {
    item.rank = idx + 1;
    item.isBestOpportunity = idx === 0;
  });

  return ranked;
}
